// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: resume/v1/resume.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resume messages
type ResumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,3,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeReply) Reset() {
	*x = ResumeReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReply) ProtoMessage() {}

func (x *ResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReply.ProtoReflect.Descriptor instead.
func (*ResumeReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeReply) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

func (x *ResumeReply) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResumeReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResumeDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Summary        string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills         []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Education      *Education             `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`
	Experience     *Experience            `protobuf:"bytes,7,opt,name=experience,proto3" json:"experience,omitempty"`
	Certifications []string               `protobuf:"bytes,8,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Languages      []string               `protobuf:"bytes,9,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeDetail) Reset() {
	*x = ResumeDetail{}
	mi := &file_resume_v1_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDetail) ProtoMessage() {}

func (x *ResumeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDetail.ProtoReflect.Descriptor instead.
func (*ResumeDetail) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResumeDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResumeDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeDetail) GetEducation() *Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ResumeDetail) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ResumeDetail) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *ResumeDetail) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type Education struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Degree         string                 `protobuf:"bytes,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Institution    string                 `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	GraduationYear string                 `protobuf:"bytes,3,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_resume_v1_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{2}
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetGraduationYear() string {
	if x != nil {
		return x.GraduationYear
	}
	return ""
}

type Experience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company          string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Duration         string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Responsibilities []string               `protobuf:"bytes,4,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Achievements     []string               `protobuf:"bytes,5,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_resume_v1_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{3}
}

func (x *Experience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Experience) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *Experience) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

// Request/Response messages
type CreateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,1,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResumeRequest) Reset() {
	*x = CreateResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRequest) ProtoMessage() {}

func (x *CreateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResumeRequest) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

type UpdateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,2,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResumeRequest) Reset() {
	*x = UpdateResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeRequest) ProtoMessage() {}

func (x *UpdateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeRequest.ProtoReflect.Descriptor instead.
func (*UpdateResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResumeRequest) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

type GetResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{6}
}

func (x *GetResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListResumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesRequest) Reset() {
	*x = ListResumesRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesRequest) ProtoMessage() {}

func (x *ListResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesRequest.ProtoReflect.Descriptor instead.
func (*ListResumesRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{7}
}

func (x *ListResumesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResumesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resumes       []*ResumeReply         `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesReply) Reset() {
	*x = ListResumesReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesReply) ProtoMessage() {}

func (x *ListResumesReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesReply.ProtoReflect.Descriptor instead.
func (*ListResumesReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{8}
}

func (x *ListResumesReply) GetResumes() []*ResumeReply {
	if x != nil {
		return x.Resumes
	}
	return nil
}

func (x *ListResumesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResumesReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeRequest) Reset() {
	*x = DeleteResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeRequest) ProtoMessage() {}

func (x *DeleteResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeReply) Reset() {
	*x = DeleteResumeReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeReply) ProtoMessage() {}

func (x *DeleteResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeReply.ProtoReflect.Descriptor instead.
func (*DeleteResumeReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResumeReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResumeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_resume_v1_resume_proto protoreflect.FileDescriptor

const file_resume_v1_resume_proto_rawDesc = "" +
	"\n" +
	"\x16resume/v1/resume.proto\x12\rapi.resume.v1\x1a\x1cgoogle/api/annotations.proto\"\xb1\x01\n" +
	"\vResumeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12@\n" +
	"\rresume_detail\x18\x03 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xb9\x02\n" +
	"\fResumeDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x126\n" +
	"\teducation\x18\x06 \x01(\v2\x18.api.resume.v1.EducationR\teducation\x129\n" +
	"\n" +
	"experience\x18\a \x01(\v2\x19.api.resume.v1.ExperienceR\n" +
	"experience\x12&\n" +
	"\x0ecertifications\x18\b \x03(\tR\x0ecertifications\x12\x1c\n" +
	"\tlanguages\x18\t \x03(\tR\tlanguages\"n\n" +
	"\tEducation\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\tR\x06degree\x12 \n" +
	"\vinstitution\x18\x02 \x01(\tR\vinstitution\x12'\n" +
	"\x0fgraduation_year\x18\x03 \x01(\tR\x0egraduationYear\"\xa8\x01\n" +
	"\n" +
	"Experience\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12*\n" +
	"\x10responsibilities\x18\x04 \x03(\tR\x10responsibilities\x12\"\n" +
	"\fachievements\x18\x05 \x03(\tR\fachievements\"W\n" +
	"\x13CreateResumeRequest\x12@\n" +
	"\rresume_detail\x18\x01 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\"g\n" +
	"\x13UpdateResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\rresume_detail\x18\x02 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\"\"\n" +
	"\x10GetResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12ListResumesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x10ListResumesReply\x124\n" +
	"\aresumes\x18\x01 \x03(\v2\x1a.api.resume.v1.ResumeReplyR\aresumes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"%\n" +
	"\x13DeleteResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x11DeleteResumeReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x04\n" +
	"\x06Resume\x12j\n" +
	"\fCreateResume\x12\".api.resume.v1.CreateResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/resumes\x12o\n" +
	"\fUpdateResume\x12\".api.resume.v1.UpdateResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/resumes/{id}\x12f\n" +
	"\tGetResume\x12\x1f.api.resume.v1.GetResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/resumes/{id}\x12j\n" +
	"\vListResumes\x12!.api.resume.v1.ListResumesRequest\x1a\x1f.api.resume.v1.ListResumesReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/resumes\x12r\n" +
	"\fDeleteResume\x12\".api.resume.v1.DeleteResumeRequest\x1a .api.resume.v1.DeleteResumeReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/resumes/{id}B,\n" +
	"\rapi.resume.v1P\x01Z\x19JobblyBE/api/resume/v1;v1b\x06proto3"

var (
	file_resume_v1_resume_proto_rawDescOnce sync.Once
	file_resume_v1_resume_proto_rawDescData []byte
)

func file_resume_v1_resume_proto_rawDescGZIP() []byte {
	file_resume_v1_resume_proto_rawDescOnce.Do(func() {
		file_resume_v1_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resume_v1_resume_proto_rawDesc), len(file_resume_v1_resume_proto_rawDesc)))
	})
	return file_resume_v1_resume_proto_rawDescData
}

var file_resume_v1_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_resume_v1_resume_proto_goTypes = []any{
	(*ResumeReply)(nil),         // 0: api.resume.v1.ResumeReply
	(*ResumeDetail)(nil),        // 1: api.resume.v1.ResumeDetail
	(*Education)(nil),           // 2: api.resume.v1.Education
	(*Experience)(nil),          // 3: api.resume.v1.Experience
	(*CreateResumeRequest)(nil), // 4: api.resume.v1.CreateResumeRequest
	(*UpdateResumeRequest)(nil), // 5: api.resume.v1.UpdateResumeRequest
	(*GetResumeRequest)(nil),    // 6: api.resume.v1.GetResumeRequest
	(*ListResumesRequest)(nil),  // 7: api.resume.v1.ListResumesRequest
	(*ListResumesReply)(nil),    // 8: api.resume.v1.ListResumesReply
	(*DeleteResumeRequest)(nil), // 9: api.resume.v1.DeleteResumeRequest
	(*DeleteResumeReply)(nil),   // 10: api.resume.v1.DeleteResumeReply
}
var file_resume_v1_resume_proto_depIdxs = []int32{
	1,  // 0: api.resume.v1.ResumeReply.resume_detail:type_name -> api.resume.v1.ResumeDetail
	2,  // 1: api.resume.v1.ResumeDetail.education:type_name -> api.resume.v1.Education
	3,  // 2: api.resume.v1.ResumeDetail.experience:type_name -> api.resume.v1.Experience
	1,  // 3: api.resume.v1.CreateResumeRequest.resume_detail:type_name -> api.resume.v1.ResumeDetail
	1,  // 4: api.resume.v1.UpdateResumeRequest.resume_detail:type_name -> api.resume.v1.ResumeDetail
	0,  // 5: api.resume.v1.ListResumesReply.resumes:type_name -> api.resume.v1.ResumeReply
	4,  // 6: api.resume.v1.Resume.CreateResume:input_type -> api.resume.v1.CreateResumeRequest
	5,  // 7: api.resume.v1.Resume.UpdateResume:input_type -> api.resume.v1.UpdateResumeRequest
	6,  // 8: api.resume.v1.Resume.GetResume:input_type -> api.resume.v1.GetResumeRequest
	7,  // 9: api.resume.v1.Resume.ListResumes:input_type -> api.resume.v1.ListResumesRequest
	9,  // 10: api.resume.v1.Resume.DeleteResume:input_type -> api.resume.v1.DeleteResumeRequest
	0,  // 11: api.resume.v1.Resume.CreateResume:output_type -> api.resume.v1.ResumeReply
	0,  // 12: api.resume.v1.Resume.UpdateResume:output_type -> api.resume.v1.ResumeReply
	0,  // 13: api.resume.v1.Resume.GetResume:output_type -> api.resume.v1.ResumeReply
	8,  // 14: api.resume.v1.Resume.ListResumes:output_type -> api.resume.v1.ListResumesReply
	10, // 15: api.resume.v1.Resume.DeleteResume:output_type -> api.resume.v1.DeleteResumeReply
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_resume_v1_resume_proto_init() }
func file_resume_v1_resume_proto_init() {
	if File_resume_v1_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_v1_resume_proto_rawDesc), len(file_resume_v1_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_v1_resume_proto_goTypes,
		DependencyIndexes: file_resume_v1_resume_proto_depIdxs,
		MessageInfos:      file_resume_v1_resume_proto_msgTypes,
	}.Build()
	File_resume_v1_resume_proto = out.File
	file_resume_v1_resume_proto_goTypes = nil
	file_resume_v1_resume_proto_depIdxs = nil
}
