// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: resume/v1/resume.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resume_CreateResume_FullMethodName = "/api.resume.v1.Resume/CreateResume"
	Resume_UpdateResume_FullMethodName = "/api.resume.v1.Resume/UpdateResume"
	Resume_GetResume_FullMethodName    = "/api.resume.v1.Resume/GetResume"
	Resume_ListResumes_FullMethodName  = "/api.resume.v1.Resume/ListResumes"
	Resume_DeleteResume_FullMethodName = "/api.resume.v1.Resume/DeleteResume"
)

// ResumeClient is the client API for Resume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeClient interface {
	// Create a new resume
	CreateResume(ctx context.Context, in *CreateResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error)
	// Update an existing resume
	UpdateResume(ctx context.Context, in *UpdateResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error)
	// Get a resume by ID
	GetResume(ctx context.Context, in *GetResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error)
	// List all resumes for the authenticated user
	ListResumes(ctx context.Context, in *ListResumesRequest, opts ...grpc.CallOption) (*ListResumesReply, error)
	// Delete a resume
	DeleteResume(ctx context.Context, in *DeleteResumeRequest, opts ...grpc.CallOption) (*DeleteResumeReply, error)
}

type resumeClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeClient(cc grpc.ClientConnInterface) ResumeClient {
	return &resumeClient{cc}
}

func (c *resumeClient) CreateResume(ctx context.Context, in *CreateResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeReply)
	err := c.cc.Invoke(ctx, Resume_CreateResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) UpdateResume(ctx context.Context, in *UpdateResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeReply)
	err := c.cc.Invoke(ctx, Resume_UpdateResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) GetResume(ctx context.Context, in *GetResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeReply)
	err := c.cc.Invoke(ctx, Resume_GetResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) ListResumes(ctx context.Context, in *ListResumesRequest, opts ...grpc.CallOption) (*ListResumesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResumesReply)
	err := c.cc.Invoke(ctx, Resume_ListResumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) DeleteResume(ctx context.Context, in *DeleteResumeRequest, opts ...grpc.CallOption) (*DeleteResumeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResumeReply)
	err := c.cc.Invoke(ctx, Resume_DeleteResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeServer is the server API for Resume service.
// All implementations must embed UnimplementedResumeServer
// for forward compatibility.
type ResumeServer interface {
	// Create a new resume
	CreateResume(context.Context, *CreateResumeRequest) (*ResumeReply, error)
	// Update an existing resume
	UpdateResume(context.Context, *UpdateResumeRequest) (*ResumeReply, error)
	// Get a resume by ID
	GetResume(context.Context, *GetResumeRequest) (*ResumeReply, error)
	// List all resumes for the authenticated user
	ListResumes(context.Context, *ListResumesRequest) (*ListResumesReply, error)
	// Delete a resume
	DeleteResume(context.Context, *DeleteResumeRequest) (*DeleteResumeReply, error)
	mustEmbedUnimplementedResumeServer()
}

// UnimplementedResumeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResumeServer struct{}

func (UnimplementedResumeServer) CreateResume(context.Context, *CreateResumeRequest) (*ResumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResume not implemented")
}
func (UnimplementedResumeServer) UpdateResume(context.Context, *UpdateResumeRequest) (*ResumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResume not implemented")
}
func (UnimplementedResumeServer) GetResume(context.Context, *GetResumeRequest) (*ResumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResume not implemented")
}
func (UnimplementedResumeServer) ListResumes(context.Context, *ListResumesRequest) (*ListResumesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResumes not implemented")
}
func (UnimplementedResumeServer) DeleteResume(context.Context, *DeleteResumeRequest) (*DeleteResumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResume not implemented")
}
func (UnimplementedResumeServer) mustEmbedUnimplementedResumeServer() {}
func (UnimplementedResumeServer) testEmbeddedByValue()                {}

// UnsafeResumeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeServer will
// result in compilation errors.
type UnsafeResumeServer interface {
	mustEmbedUnimplementedResumeServer()
}

func RegisterResumeServer(s grpc.ServiceRegistrar, srv ResumeServer) {
	// If the following call pancis, it indicates UnimplementedResumeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resume_ServiceDesc, srv)
}

func _Resume_CreateResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).CreateResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resume_CreateResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).CreateResume(ctx, req.(*CreateResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_UpdateResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).UpdateResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resume_UpdateResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).UpdateResume(ctx, req.(*UpdateResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_GetResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).GetResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resume_GetResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).GetResume(ctx, req.(*GetResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_ListResumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).ListResumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resume_ListResumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).ListResumes(ctx, req.(*ListResumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_DeleteResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).DeleteResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resume_DeleteResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).DeleteResume(ctx, req.(*DeleteResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resume_ServiceDesc is the grpc.ServiceDesc for Resume service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resume_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.resume.v1.Resume",
	HandlerType: (*ResumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResume",
			Handler:    _Resume_CreateResume_Handler,
		},
		{
			MethodName: "UpdateResume",
			Handler:    _Resume_UpdateResume_Handler,
		},
		{
			MethodName: "GetResume",
			Handler:    _Resume_GetResume_Handler,
		},
		{
			MethodName: "ListResumes",
			Handler:    _Resume_ListResumes_Handler,
		},
		{
			MethodName: "DeleteResume",
			Handler:    _Resume_DeleteResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resume/v1/resume.proto",
}
