// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: resume/v1/resume.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resume messages
type ResumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,3,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeReply) Reset() {
	*x = ResumeReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReply) ProtoMessage() {}

func (x *ResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReply.ProtoReflect.Descriptor instead.
func (*ResumeReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeReply) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

func (x *ResumeReply) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResumeReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResumeDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Summary        string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills         []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Education      []*Education           `protobuf:"bytes,6,rep,name=education,proto3" json:"education,omitempty"`
	Experience     []*Experience          `protobuf:"bytes,7,rep,name=experience,proto3" json:"experience,omitempty"`
	Projects       []*Project             `protobuf:"bytes,8,rep,name=projects,proto3" json:"projects,omitempty"`
	Certifications []string               `protobuf:"bytes,9,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Languages      []string               `protobuf:"bytes,10,rep,name=languages,proto3" json:"languages,omitempty"`
	Achievements   []string               `protobuf:"bytes,11,rep,name=achievements,proto3" json:"achievements,omitempty"`
	Evaluations    []*ResumeEvaluation    `protobuf:"bytes,12,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeDetail) Reset() {
	*x = ResumeDetail{}
	mi := &file_resume_v1_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDetail) ProtoMessage() {}

func (x *ResumeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDetail.ProtoReflect.Descriptor instead.
func (*ResumeDetail) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResumeDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResumeDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeDetail) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ResumeDetail) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ResumeDetail) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ResumeDetail) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *ResumeDetail) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *ResumeDetail) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *ResumeDetail) GetEvaluations() []*ResumeEvaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

type Education struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Degree         string                 `protobuf:"bytes,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Institution    string                 `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	GraduationYear string                 `protobuf:"bytes,3,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_resume_v1_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{2}
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetGraduationYear() string {
	if x != nil {
		return x.GraduationYear
	}
	return ""
}

func (x *Education) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Experience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company          string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Duration         string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities []string               `protobuf:"bytes,5,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Achievements     []string               `protobuf:"bytes,6,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_resume_v1_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{3}
}

func (x *Experience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Experience) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *Experience) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Technologies  []string               `protobuf:"bytes,3,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Achievements  []string               `protobuf:"bytes,7,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_resume_v1_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{4}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Project) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Project) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Project) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Project) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type ResumeScoreBreakdown struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SkillsScore       float64                `protobuf:"fixed64,1,opt,name=skills_score,json=skillsScore,proto3" json:"skills_score,omitempty"`
	ExperienceScore   float64                `protobuf:"fixed64,2,opt,name=experience_score,json=experienceScore,proto3" json:"experience_score,omitempty"`
	EducationScore    float64                `protobuf:"fixed64,3,opt,name=education_score,json=educationScore,proto3" json:"education_score,omitempty"`
	CompletenessScore float64                `protobuf:"fixed64,4,opt,name=completeness_score,json=completenessScore,proto3" json:"completeness_score,omitempty"`
	JobAlignmentScore float64                `protobuf:"fixed64,5,opt,name=job_alignment_score,json=jobAlignmentScore,proto3" json:"job_alignment_score,omitempty"`
	PresentationScore float64                `protobuf:"fixed64,6,opt,name=presentation_score,json=presentationScore,proto3" json:"presentation_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResumeScoreBreakdown) Reset() {
	*x = ResumeScoreBreakdown{}
	mi := &file_resume_v1_resume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScoreBreakdown) ProtoMessage() {}

func (x *ResumeScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ResumeScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeScoreBreakdown) GetSkillsScore() float64 {
	if x != nil {
		return x.SkillsScore
	}
	return 0
}

func (x *ResumeScoreBreakdown) GetExperienceScore() float64 {
	if x != nil {
		return x.ExperienceScore
	}
	return 0
}

func (x *ResumeScoreBreakdown) GetEducationScore() float64 {
	if x != nil {
		return x.EducationScore
	}
	return 0
}

func (x *ResumeScoreBreakdown) GetCompletenessScore() float64 {
	if x != nil {
		return x.CompletenessScore
	}
	return 0
}

func (x *ResumeScoreBreakdown) GetJobAlignmentScore() float64 {
	if x != nil {
		return x.JobAlignmentScore
	}
	return 0
}

func (x *ResumeScoreBreakdown) GetPresentationScore() float64 {
	if x != nil {
		return x.PresentationScore
	}
	return 0
}

type ResumeCVEdit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FieldPath      string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Action         string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	CurrentValue   string                 `protobuf:"bytes,3,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	SuggestedValue string                 `protobuf:"bytes,4,opt,name=suggested_value,json=suggestedValue,proto3" json:"suggested_value,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Priority       string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	ImpactScore    float64                `protobuf:"fixed64,7,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // null/empty: new, "rejected": user rejected, "accepted": user accepted
	Id             string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`         // unique identifier for the edit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeCVEdit) Reset() {
	*x = ResumeCVEdit{}
	mi := &file_resume_v1_resume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeCVEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCVEdit) ProtoMessage() {}

func (x *ResumeCVEdit) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCVEdit.ProtoReflect.Descriptor instead.
func (*ResumeCVEdit) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeCVEdit) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *ResumeCVEdit) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResumeCVEdit) GetCurrentValue() string {
	if x != nil {
		return x.CurrentValue
	}
	return ""
}

func (x *ResumeCVEdit) GetSuggestedValue() string {
	if x != nil {
		return x.SuggestedValue
	}
	return ""
}

func (x *ResumeCVEdit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResumeCVEdit) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ResumeCVEdit) GetImpactScore() float64 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

func (x *ResumeCVEdit) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResumeCVEdit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeEvaluation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CvName          string                 `protobuf:"bytes,1,opt,name=cv_name,json=cvName,proto3" json:"cv_name,omitempty"`
	OverallScore    float64                `protobuf:"fixed64,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Grade           string                 `protobuf:"bytes,3,opt,name=grade,proto3" json:"grade,omitempty"`
	ScoreBreakdown  *ResumeScoreBreakdown  `protobuf:"bytes,4,opt,name=score_breakdown,json=scoreBreakdown,proto3" json:"score_breakdown,omitempty"`
	Strengths       []string               `protobuf:"bytes,5,rep,name=strengths,proto3" json:"strengths,omitempty"`
	Weaknesses      []string               `protobuf:"bytes,6,rep,name=weaknesses,proto3" json:"weaknesses,omitempty"`
	Recommendations []string               `protobuf:"bytes,7,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	CvEdits         []*ResumeCVEdit        `protobuf:"bytes,8,rep,name=cv_edits,json=cvEdits,proto3" json:"cv_edits,omitempty"`
	JobsAnalyzed    int32                  `protobuf:"varint,9,opt,name=jobs_analyzed,json=jobsAnalyzed,proto3" json:"jobs_analyzed,omitempty"`
	EvaluatedAt     string                 `protobuf:"bytes,10,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResumeEvaluation) Reset() {
	*x = ResumeEvaluation{}
	mi := &file_resume_v1_resume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeEvaluation) ProtoMessage() {}

func (x *ResumeEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeEvaluation.ProtoReflect.Descriptor instead.
func (*ResumeEvaluation) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeEvaluation) GetCvName() string {
	if x != nil {
		return x.CvName
	}
	return ""
}

func (x *ResumeEvaluation) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *ResumeEvaluation) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *ResumeEvaluation) GetScoreBreakdown() *ResumeScoreBreakdown {
	if x != nil {
		return x.ScoreBreakdown
	}
	return nil
}

func (x *ResumeEvaluation) GetStrengths() []string {
	if x != nil {
		return x.Strengths
	}
	return nil
}

func (x *ResumeEvaluation) GetWeaknesses() []string {
	if x != nil {
		return x.Weaknesses
	}
	return nil
}

func (x *ResumeEvaluation) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *ResumeEvaluation) GetCvEdits() []*ResumeCVEdit {
	if x != nil {
		return x.CvEdits
	}
	return nil
}

func (x *ResumeEvaluation) GetJobsAnalyzed() int32 {
	if x != nil {
		return x.JobsAnalyzed
	}
	return 0
}

func (x *ResumeEvaluation) GetEvaluatedAt() string {
	if x != nil {
		return x.EvaluatedAt
	}
	return ""
}

// Request/Response messages
type CreateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,1,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResumeRequest) Reset() {
	*x = CreateResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRequest) ProtoMessage() {}

func (x *CreateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResumeRequest) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

type UpdateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,2,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResumeRequest) Reset() {
	*x = UpdateResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeRequest) ProtoMessage() {}

func (x *UpdateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeRequest.ProtoReflect.Descriptor instead.
func (*UpdateResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResumeRequest) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

type GetResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{10}
}

func (x *GetResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListResumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesRequest) Reset() {
	*x = ListResumesRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesRequest) ProtoMessage() {}

func (x *ListResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesRequest.ProtoReflect.Descriptor instead.
func (*ListResumesRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{11}
}

func (x *ListResumesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResumesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resumes       []*ResumeReply         `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesReply) Reset() {
	*x = ListResumesReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesReply) ProtoMessage() {}

func (x *ListResumesReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesReply.ProtoReflect.Descriptor instead.
func (*ListResumesReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{12}
}

func (x *ListResumesReply) GetResumes() []*ResumeReply {
	if x != nil {
		return x.Resumes
	}
	return nil
}

func (x *ListResumesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResumesReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeRequest) Reset() {
	*x = DeleteResumeRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeRequest) ProtoMessage() {}

func (x *DeleteResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeReply) Reset() {
	*x = DeleteResumeReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeReply) ProtoMessage() {}

func (x *DeleteResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeReply.ProtoReflect.Descriptor instead.
func (*DeleteResumeReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteResumeReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResumeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateCVDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeDetail  *ResumeDetail          `protobuf:"bytes,1,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	FieldTag      string                 `protobuf:"bytes,2,opt,name=field_tag,json=fieldTag,proto3" json:"field_tag,omitempty"`
	CurrentInput  string                 `protobuf:"bytes,3,opt,name=current_input,json=currentInput,proto3" json:"current_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCVDescriptionRequest) Reset() {
	*x = GenerateCVDescriptionRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCVDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCVDescriptionRequest) ProtoMessage() {}

func (x *GenerateCVDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCVDescriptionRequest.ProtoReflect.Descriptor instead.
func (*GenerateCVDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateCVDescriptionRequest) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

func (x *GenerateCVDescriptionRequest) GetFieldTag() string {
	if x != nil {
		return x.FieldTag
	}
	return ""
}

func (x *GenerateCVDescriptionRequest) GetCurrentInput() string {
	if x != nil {
		return x.CurrentInput
	}
	return ""
}

type GenerateCVDescriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCVDescriptionReply) Reset() {
	*x = GenerateCVDescriptionReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCVDescriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCVDescriptionReply) ProtoMessage() {}

func (x *GenerateCVDescriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCVDescriptionReply.ProtoReflect.Descriptor instead.
func (*GenerateCVDescriptionReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateCVDescriptionReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCVEditStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	EditId        string                 `protobuf:"bytes,2,opt,name=edit_id,json=editId,proto3" json:"edit_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "accepted" or "rejected"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCVEditStatusRequest) Reset() {
	*x = UpdateCVEditStatusRequest{}
	mi := &file_resume_v1_resume_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCVEditStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCVEditStatusRequest) ProtoMessage() {}

func (x *UpdateCVEditStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCVEditStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCVEditStatusRequest) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCVEditStatusRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *UpdateCVEditStatusRequest) GetEditId() string {
	if x != nil {
		return x.EditId
	}
	return ""
}

func (x *UpdateCVEditStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCVEditStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCVEditStatusReply) Reset() {
	*x = UpdateCVEditStatusReply{}
	mi := &file_resume_v1_resume_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCVEditStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCVEditStatusReply) ProtoMessage() {}

func (x *UpdateCVEditStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_v1_resume_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCVEditStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateCVEditStatusReply) Descriptor() ([]byte, []int) {
	return file_resume_v1_resume_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCVEditStatusReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCVEditStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_resume_v1_resume_proto protoreflect.FileDescriptor

const file_resume_v1_resume_proto_rawDesc = "" +
	"\n" +
	"\x16resume/v1/resume.proto\x12\rapi.resume.v1\x1a\x1cgoogle/api/annotations.proto\"\xb1\x01\n" +
	"\vResumeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12@\n" +
	"\rresume_detail\x18\x03 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xd4\x03\n" +
	"\fResumeDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x126\n" +
	"\teducation\x18\x06 \x03(\v2\x18.api.resume.v1.EducationR\teducation\x129\n" +
	"\n" +
	"experience\x18\a \x03(\v2\x19.api.resume.v1.ExperienceR\n" +
	"experience\x122\n" +
	"\bprojects\x18\b \x03(\v2\x16.api.resume.v1.ProjectR\bprojects\x12&\n" +
	"\x0ecertifications\x18\t \x03(\tR\x0ecertifications\x12\x1c\n" +
	"\tlanguages\x18\n" +
	" \x03(\tR\tlanguages\x12\"\n" +
	"\fachievements\x18\v \x03(\tR\fachievements\x12A\n" +
	"\vevaluations\x18\f \x03(\v2\x1f.api.resume.v1.ResumeEvaluationR\vevaluations\"\x90\x01\n" +
	"\tEducation\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\tR\x06degree\x12 \n" +
	"\vinstitution\x18\x02 \x01(\tR\vinstitution\x12'\n" +
	"\x0fgraduation_year\x18\x03 \x01(\tR\x0egraduationYear\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xca\x01\n" +
	"\n" +
	"Experience\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\x05 \x03(\tR\x10responsibilities\x12\"\n" +
	"\fachievements\x18\x06 \x03(\tR\fachievements\"\xc9\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\ftechnologies\x18\x03 \x03(\tR\ftechnologies\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\"\n" +
	"\fachievements\x18\a \x03(\tR\fachievements\"\x9b\x02\n" +
	"\x14ResumeScoreBreakdown\x12!\n" +
	"\fskills_score\x18\x01 \x01(\x01R\vskillsScore\x12)\n" +
	"\x10experience_score\x18\x02 \x01(\x01R\x0fexperienceScore\x12'\n" +
	"\x0feducation_score\x18\x03 \x01(\x01R\x0eeducationScore\x12-\n" +
	"\x12completeness_score\x18\x04 \x01(\x01R\x11completenessScore\x12.\n" +
	"\x13job_alignment_score\x18\x05 \x01(\x01R\x11jobAlignmentScore\x12-\n" +
	"\x12presentation_score\x18\x06 \x01(\x01R\x11presentationScore\"\x92\x02\n" +
	"\fResumeCVEdit\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12#\n" +
	"\rcurrent_value\x18\x03 \x01(\tR\fcurrentValue\x12'\n" +
	"\x0fsuggested_value\x18\x04 \x01(\tR\x0esuggestedValue\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12!\n" +
	"\fimpact_score\x18\a \x01(\x01R\vimpactScore\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02id\"\x9c\x03\n" +
	"\x10ResumeEvaluation\x12\x17\n" +
	"\acv_name\x18\x01 \x01(\tR\x06cvName\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x01R\foverallScore\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\tR\x05grade\x12L\n" +
	"\x0fscore_breakdown\x18\x04 \x01(\v2#.api.resume.v1.ResumeScoreBreakdownR\x0escoreBreakdown\x12\x1c\n" +
	"\tstrengths\x18\x05 \x03(\tR\tstrengths\x12\x1e\n" +
	"\n" +
	"weaknesses\x18\x06 \x03(\tR\n" +
	"weaknesses\x12(\n" +
	"\x0frecommendations\x18\a \x03(\tR\x0frecommendations\x126\n" +
	"\bcv_edits\x18\b \x03(\v2\x1b.api.resume.v1.ResumeCVEditR\acvEdits\x12#\n" +
	"\rjobs_analyzed\x18\t \x01(\x05R\fjobsAnalyzed\x12!\n" +
	"\fevaluated_at\x18\n" +
	" \x01(\tR\vevaluatedAt\"W\n" +
	"\x13CreateResumeRequest\x12@\n" +
	"\rresume_detail\x18\x01 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\"g\n" +
	"\x13UpdateResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\rresume_detail\x18\x02 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\"\"\n" +
	"\x10GetResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12ListResumesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x10ListResumesReply\x124\n" +
	"\aresumes\x18\x01 \x03(\v2\x1a.api.resume.v1.ResumeReplyR\aresumes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"%\n" +
	"\x13DeleteResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x11DeleteResumeReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa2\x01\n" +
	"\x1cGenerateCVDescriptionRequest\x12@\n" +
	"\rresume_detail\x18\x01 \x01(\v2\x1b.api.resume.v1.ResumeDetailR\fresumeDetail\x12\x1b\n" +
	"\tfield_tag\x18\x02 \x01(\tR\bfieldTag\x12#\n" +
	"\rcurrent_input\x18\x03 \x01(\tR\fcurrentInput\"6\n" +
	"\x1aGenerateCVDescriptionReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"i\n" +
	"\x19UpdateCVEditStatusRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x17\n" +
	"\aedit_id\x18\x02 \x01(\tR\x06editId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"M\n" +
	"\x17UpdateCVEditStatusReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfb\x06\n" +
	"\x06Resume\x12j\n" +
	"\fCreateResume\x12\".api.resume.v1.CreateResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/resumes\x12o\n" +
	"\fUpdateResume\x12\".api.resume.v1.UpdateResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/resumes/{id}\x12f\n" +
	"\tGetResume\x12\x1f.api.resume.v1.GetResumeRequest\x1a\x1a.api.resume.v1.ResumeReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/resumes/{id}\x12j\n" +
	"\vListResumes\x12!.api.resume.v1.ListResumesRequest\x1a\x1f.api.resume.v1.ListResumesReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/resumes\x12r\n" +
	"\fDeleteResume\x12\".api.resume.v1.DeleteResumeRequest\x1a .api.resume.v1.DeleteResumeReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/resumes/{id}\x12\xa0\x01\n" +
	"\x15GenerateCVDescription\x12+.api.resume.v1.GenerateCVDescriptionRequest\x1a).api.resume.v1.GenerateCVDescriptionReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/resumes/generate-description\x12\xa8\x01\n" +
	"\x12UpdateCVEditStatus\x12(.api.resume.v1.UpdateCVEditStatusRequest\x1a&.api.resume.v1.UpdateCVEditStatusReply\"@\x82\xd3\xe4\x93\x02::\x01*\x1a5/api/v1/resumes/{resume_id}/cv-edits/{edit_id}/statusB,\n" +
	"\rapi.resume.v1P\x01Z\x19JobblyBE/api/resume/v1;v1b\x06proto3"

var (
	file_resume_v1_resume_proto_rawDescOnce sync.Once
	file_resume_v1_resume_proto_rawDescData []byte
)

func file_resume_v1_resume_proto_rawDescGZIP() []byte {
	file_resume_v1_resume_proto_rawDescOnce.Do(func() {
		file_resume_v1_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resume_v1_resume_proto_rawDesc), len(file_resume_v1_resume_proto_rawDesc)))
	})
	return file_resume_v1_resume_proto_rawDescData
}

var file_resume_v1_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_resume_v1_resume_proto_goTypes = []any{
	(*ResumeReply)(nil),                  // 0: api.resume.v1.ResumeReply
	(*ResumeDetail)(nil),                 // 1: api.resume.v1.ResumeDetail
	(*Education)(nil),                    // 2: api.resume.v1.Education
	(*Experience)(nil),                   // 3: api.resume.v1.Experience
	(*Project)(nil),                      // 4: api.resume.v1.Project
	(*ResumeScoreBreakdown)(nil),         // 5: api.resume.v1.ResumeScoreBreakdown
	(*ResumeCVEdit)(nil),                 // 6: api.resume.v1.ResumeCVEdit
	(*ResumeEvaluation)(nil),             // 7: api.resume.v1.ResumeEvaluation
	(*CreateResumeRequest)(nil),          // 8: api.resume.v1.CreateResumeRequest
	(*UpdateResumeRequest)(nil),          // 9: api.resume.v1.UpdateResumeRequest
	(*GetResumeRequest)(nil),             // 10: api.resume.v1.GetResumeRequest
	(*ListResumesRequest)(nil),           // 11: api.resume.v1.ListResumesRequest
	(*ListResumesReply)(nil),             // 12: api.resume.v1.ListResumesReply
	(*DeleteResumeRequest)(nil),          // 13: api.resume.v1.DeleteResumeRequest
	(*DeleteResumeReply)(nil),            // 14: api.resume.v1.DeleteResumeReply
	(*GenerateCVDescriptionRequest)(nil), // 15: api.resume.v1.GenerateCVDescriptionRequest
	(*GenerateCVDescriptionReply)(nil),   // 16: api.resume.v1.GenerateCVDescriptionReply
	(*UpdateCVEditStatusRequest)(nil),    // 17: api.resume.v1.UpdateCVEditStatusRequest
	(*UpdateCVEditStatusReply)(nil),      // 18: api.resume.v1.UpdateCVEditStatusReply
}
var file_resume_v1_resume_proto_depIdxs = []int32{
	1,  // 0: api.resume.v1.ResumeReply.resume_detail:type_name -> api.resume.v1.ResumeDetail
	2,  // 1: api.resume.v1.ResumeDetail.education:type_name -> api.resume.v1.Education
	3,  // 2: api.resume.v1.ResumeDetail.experience:type_name -> api.resume.v1.Experience
	4,  // 3: api.resume.v1.ResumeDetail.projects:type_name -> api.resume.v1.Project
	7,  // 4: api.resume.v1.ResumeDetail.evaluations:type_name -> api.resume.v1.ResumeEvaluation
	5,  // 5: api.resume.v1.ResumeEvaluation.score_breakdown:type_name -> api.resume.v1.ResumeScoreBreakdown
	6,  // 6: api.resume.v1.ResumeEvaluation.cv_edits:type_name -> api.resume.v1.ResumeCVEdit
	1,  // 7: api.resume.v1.CreateResumeRequest.resume_detail:type_name -> api.resume.v1.ResumeDetail
	1,  // 8: api.resume.v1.UpdateResumeRequest.resume_detail:type_name -> api.resume.v1.ResumeDetail
	0,  // 9: api.resume.v1.ListResumesReply.resumes:type_name -> api.resume.v1.ResumeReply
	1,  // 10: api.resume.v1.GenerateCVDescriptionRequest.resume_detail:type_name -> api.resume.v1.ResumeDetail
	8,  // 11: api.resume.v1.Resume.CreateResume:input_type -> api.resume.v1.CreateResumeRequest
	9,  // 12: api.resume.v1.Resume.UpdateResume:input_type -> api.resume.v1.UpdateResumeRequest
	10, // 13: api.resume.v1.Resume.GetResume:input_type -> api.resume.v1.GetResumeRequest
	11, // 14: api.resume.v1.Resume.ListResumes:input_type -> api.resume.v1.ListResumesRequest
	13, // 15: api.resume.v1.Resume.DeleteResume:input_type -> api.resume.v1.DeleteResumeRequest
	15, // 16: api.resume.v1.Resume.GenerateCVDescription:input_type -> api.resume.v1.GenerateCVDescriptionRequest
	17, // 17: api.resume.v1.Resume.UpdateCVEditStatus:input_type -> api.resume.v1.UpdateCVEditStatusRequest
	0,  // 18: api.resume.v1.Resume.CreateResume:output_type -> api.resume.v1.ResumeReply
	0,  // 19: api.resume.v1.Resume.UpdateResume:output_type -> api.resume.v1.ResumeReply
	0,  // 20: api.resume.v1.Resume.GetResume:output_type -> api.resume.v1.ResumeReply
	12, // 21: api.resume.v1.Resume.ListResumes:output_type -> api.resume.v1.ListResumesReply
	14, // 22: api.resume.v1.Resume.DeleteResume:output_type -> api.resume.v1.DeleteResumeReply
	16, // 23: api.resume.v1.Resume.GenerateCVDescription:output_type -> api.resume.v1.GenerateCVDescriptionReply
	18, // 24: api.resume.v1.Resume.UpdateCVEditStatus:output_type -> api.resume.v1.UpdateCVEditStatusReply
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_resume_v1_resume_proto_init() }
func file_resume_v1_resume_proto_init() {
	if File_resume_v1_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_v1_resume_proto_rawDesc), len(file_resume_v1_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_v1_resume_proto_goTypes,
		DependencyIndexes: file_resume_v1_resume_proto_depIdxs,
		MessageInfos:      file_resume_v1_resume_proto_msgTypes,
	}.Build()
	File_resume_v1_resume_proto = out.File
	file_resume_v1_resume_proto_goTypes = nil
	file_resume_v1_resume_proto_depIdxs = nil
}
