// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.1
// source: resume/v1/resume.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationResumeCreateResume = "/api.resume.v1.Resume/CreateResume"
const OperationResumeDeleteResume = "/api.resume.v1.Resume/DeleteResume"
const OperationResumeGetResume = "/api.resume.v1.Resume/GetResume"
const OperationResumeListResumes = "/api.resume.v1.Resume/ListResumes"
const OperationResumeUpdateResume = "/api.resume.v1.Resume/UpdateResume"

type ResumeHTTPServer interface {
	// CreateResume Create a new resume
	CreateResume(context.Context, *CreateResumeRequest) (*ResumeReply, error)
	// DeleteResume Delete a resume
	DeleteResume(context.Context, *DeleteResumeRequest) (*DeleteResumeReply, error)
	// GetResume Get a resume by ID
	GetResume(context.Context, *GetResumeRequest) (*ResumeReply, error)
	// ListResumes List all resumes for the authenticated user
	ListResumes(context.Context, *ListResumesRequest) (*ListResumesReply, error)
	// UpdateResume Update an existing resume
	UpdateResume(context.Context, *UpdateResumeRequest) (*ResumeReply, error)
}

func RegisterResumeHTTPServer(s *http.Server, srv ResumeHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/resumes", _Resume_CreateResume0_HTTP_Handler(srv))
	r.PUT("/api/v1/resumes/{id}", _Resume_UpdateResume0_HTTP_Handler(srv))
	r.GET("/api/v1/resumes/{id}", _Resume_GetResume0_HTTP_Handler(srv))
	r.GET("/api/v1/resumes", _Resume_ListResumes0_HTTP_Handler(srv))
	r.DELETE("/api/v1/resumes/{id}", _Resume_DeleteResume0_HTTP_Handler(srv))
}

func _Resume_CreateResume0_HTTP_Handler(srv ResumeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateResumeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResumeCreateResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateResume(ctx, req.(*CreateResumeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResumeReply)
		return ctx.Result(200, reply)
	}
}

func _Resume_UpdateResume0_HTTP_Handler(srv ResumeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateResumeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResumeUpdateResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateResume(ctx, req.(*UpdateResumeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResumeReply)
		return ctx.Result(200, reply)
	}
}

func _Resume_GetResume0_HTTP_Handler(srv ResumeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetResumeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResumeGetResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetResume(ctx, req.(*GetResumeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResumeReply)
		return ctx.Result(200, reply)
	}
}

func _Resume_ListResumes0_HTTP_Handler(srv ResumeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListResumesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResumeListResumes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListResumes(ctx, req.(*ListResumesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListResumesReply)
		return ctx.Result(200, reply)
	}
}

func _Resume_DeleteResume0_HTTP_Handler(srv ResumeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteResumeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResumeDeleteResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteResume(ctx, req.(*DeleteResumeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteResumeReply)
		return ctx.Result(200, reply)
	}
}

type ResumeHTTPClient interface {
	// CreateResume Create a new resume
	CreateResume(ctx context.Context, req *CreateResumeRequest, opts ...http.CallOption) (rsp *ResumeReply, err error)
	// DeleteResume Delete a resume
	DeleteResume(ctx context.Context, req *DeleteResumeRequest, opts ...http.CallOption) (rsp *DeleteResumeReply, err error)
	// GetResume Get a resume by ID
	GetResume(ctx context.Context, req *GetResumeRequest, opts ...http.CallOption) (rsp *ResumeReply, err error)
	// ListResumes List all resumes for the authenticated user
	ListResumes(ctx context.Context, req *ListResumesRequest, opts ...http.CallOption) (rsp *ListResumesReply, err error)
	// UpdateResume Update an existing resume
	UpdateResume(ctx context.Context, req *UpdateResumeRequest, opts ...http.CallOption) (rsp *ResumeReply, err error)
}

type ResumeHTTPClientImpl struct {
	cc *http.Client
}

func NewResumeHTTPClient(client *http.Client) ResumeHTTPClient {
	return &ResumeHTTPClientImpl{client}
}

// CreateResume Create a new resume
func (c *ResumeHTTPClientImpl) CreateResume(ctx context.Context, in *CreateResumeRequest, opts ...http.CallOption) (*ResumeReply, error) {
	var out ResumeReply
	pattern := "/api/v1/resumes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationResumeCreateResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteResume Delete a resume
func (c *ResumeHTTPClientImpl) DeleteResume(ctx context.Context, in *DeleteResumeRequest, opts ...http.CallOption) (*DeleteResumeReply, error) {
	var out DeleteResumeReply
	pattern := "/api/v1/resumes/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResumeDeleteResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetResume Get a resume by ID
func (c *ResumeHTTPClientImpl) GetResume(ctx context.Context, in *GetResumeRequest, opts ...http.CallOption) (*ResumeReply, error) {
	var out ResumeReply
	pattern := "/api/v1/resumes/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResumeGetResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListResumes List all resumes for the authenticated user
func (c *ResumeHTTPClientImpl) ListResumes(ctx context.Context, in *ListResumesRequest, opts ...http.CallOption) (*ListResumesReply, error) {
	var out ListResumesReply
	pattern := "/api/v1/resumes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResumeListResumes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateResume Update an existing resume
func (c *ResumeHTTPClientImpl) UpdateResume(ctx context.Context, in *UpdateResumeRequest, opts ...http.CallOption) (*ResumeReply, error) {
	var out ResumeReply
	pattern := "/api/v1/resumes/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationResumeUpdateResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
