// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsErrorReasonUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ERROR_REASON_UNSPECIFIED.String() && e.Code == 500
}

func ErrorErrorReasonUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ERROR_REASON_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsSystemError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SYSTEM_ERROR.String() && e.Code == 500
}

func ErrorSystemError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SYSTEM_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsDataRequestInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_REQUEST_INVALID.String() && e.Code == 400
}

func ErrorDataRequestInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_REQUEST_INVALID.String(), fmt.Sprintf(format, args...))
}

// Job related errors
func IsJobNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JOB_NOT_FOUND.String() && e.Code == 404
}

// Job related errors
func ErrorJobNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_JOB_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsJobAlreadySaved(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JOB_ALREADY_SAVED.String() && e.Code == 400
}

func ErrorJobAlreadySaved(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_JOB_ALREADY_SAVED.String(), fmt.Sprintf(format, args...))
}

func IsJobNotSaved(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JOB_NOT_SAVED.String() && e.Code == 400
}

func ErrorJobNotSaved(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_JOB_NOT_SAVED.String(), fmt.Sprintf(format, args...))
}
