// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: user/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	ErrorReason_SYSTEM_ERROR             ErrorReason = 1
	ErrorReason_DATA_REQUEST_INVALID     ErrorReason = 2
	// Job related errors
	ErrorReason_JOB_NOT_FOUND     ErrorReason = 10
	ErrorReason_JOB_ALREADY_SAVED ErrorReason = 11
	ErrorReason_JOB_NOT_SAVED     ErrorReason = 12
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "SYSTEM_ERROR",
		2:  "DATA_REQUEST_INVALID",
		10: "JOB_NOT_FOUND",
		11: "JOB_ALREADY_SAVED",
		12: "JOB_NOT_SAVED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"SYSTEM_ERROR":             1,
		"DATA_REQUEST_INVALID":     2,
		"JOB_NOT_FOUND":            10,
		"JOB_ALREADY_SAVED":        11,
		"JOB_NOT_SAVED":            12,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/error_reason.proto\x12\vapi.user.v1\x1a\x13errors/errors.proto*\xb8\x01\n" +
	"\vErrorReason\x12\"\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x16\n" +
	"\fSYSTEM_ERROR\x10\x01\x1a\x04\xa8E\xf4\x03\x12\x1e\n" +
	"\x14DATA_REQUEST_INVALID\x10\x02\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\rJOB_NOT_FOUND\x10\n" +
	"\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x11JOB_ALREADY_SAVED\x10\v\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\rJOB_NOT_SAVED\x10\f\x1a\x04\xa8E\x90\x03B(\n" +
	"\vapi.user.v1P\x01Z\x17JobblyBE/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_user_v1_error_reason_proto_rawDescData []byte
)

func file_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)))
	})
	return file_user_v1_error_reason_proto_rawDescData
}

var file_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.user.v1.ErrorReason
}
var file_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_error_reason_proto_init() }
func file_user_v1_error_reason_proto_init() {
	if File_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_user_v1_error_reason_proto = out.File
	file_user_v1_error_reason_proto_goTypes = nil
	file_user_v1_error_reason_proto_depIdxs = nil
}
