// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrackingJDTOSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TimeOnSight   int32                  `protobuf:"varint,2,opt,name=time_on_sight,json=timeOnSight,proto3" json:"time_on_sight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackingJDTOSRequest) Reset() {
	*x = CreateTrackingJDTOSRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingJDTOSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingJDTOSRequest) ProtoMessage() {}

func (x *CreateTrackingJDTOSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingJDTOSRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackingJDTOSRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrackingJDTOSRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateTrackingJDTOSRequest) GetTimeOnSight() int32 {
	if x != nil {
		return x.TimeOnSight
	}
	return 0
}

type CreateTrackingJDTOSReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackingJDTOSReply) Reset() {
	*x = CreateTrackingJDTOSReply{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingJDTOSReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingJDTOSReply) ProtoMessage() {}

func (x *CreateTrackingJDTOSReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingJDTOSReply.ProtoReflect.Descriptor instead.
func (*CreateTrackingJDTOSReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

type SaveJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveJobRequest) Reset() {
	*x = SaveJobRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobRequest) ProtoMessage() {}

func (x *SaveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobRequest.ProtoReflect.Descriptor instead.
func (*SaveJobRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *SaveJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SaveJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveJobReply) Reset() {
	*x = SaveJobReply{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobReply) ProtoMessage() {}

func (x *SaveJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobReply.ProtoReflect.Descriptor instead.
func (*SaveJobReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *SaveJobReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveJobReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnsaveJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsaveJobRequest) Reset() {
	*x = UnsaveJobRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsaveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsaveJobRequest) ProtoMessage() {}

func (x *UnsaveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsaveJobRequest.ProtoReflect.Descriptor instead.
func (*UnsaveJobRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UnsaveJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type UnsaveJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsaveJobReply) Reset() {
	*x = UnsaveJobReply{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsaveJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsaveJobReply) ProtoMessage() {}

func (x *UnsaveJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsaveJobReply.ProtoReflect.Descriptor instead.
func (*UnsaveJobReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UnsaveJobReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnsaveJobReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSavedJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedJobsRequest) Reset() {
	*x = GetSavedJobsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedJobsRequest) ProtoMessage() {}

func (x *GetSavedJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedJobsRequest.ProtoReflect.Descriptor instead.
func (*GetSavedJobsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetSavedJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSavedJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSavedJobsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobPosting          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedJobsReply) Reset() {
	*x = GetSavedJobsReply{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedJobsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedJobsReply) ProtoMessage() {}

func (x *GetSavedJobsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedJobsReply.ProtoReflect.Descriptor instead.
func (*GetSavedJobsReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetSavedJobsReply) GetJobs() []*JobPosting {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetSavedJobsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSavedJobsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSavedJobsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// JobPosting message (same structure as in job.proto)
type JobPosting struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId             string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Title                 string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Level                 string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	JobType               string                 `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	SalaryMin             float64                `protobuf:"fixed64,6,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax             float64                `protobuf:"fixed64,7,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	SalaryCurrency        string                 `protobuf:"bytes,8,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Location              string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	PostedAt              string                 `protobuf:"bytes,10,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	ExperienceRequirement string                 `protobuf:"bytes,11,opt,name=experience_requirement,json=experienceRequirement,proto3" json:"experience_requirement,omitempty"`
	Description           string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities      string                 `protobuf:"bytes,13,opt,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Requirements          string                 `protobuf:"bytes,14,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Benefits              string                 `protobuf:"bytes,15,opt,name=benefits,proto3" json:"benefits,omitempty"`
	JobTech               []string               `protobuf:"bytes,16,rep,name=job_tech,json=jobTech,proto3" json:"job_tech,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JobPosting) Reset() {
	*x = JobPosting{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPosting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPosting) ProtoMessage() {}

func (x *JobPosting) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPosting.ProtoReflect.Descriptor instead.
func (*JobPosting) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *JobPosting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobPosting) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *JobPosting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobPosting) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *JobPosting) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobPosting) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *JobPosting) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *JobPosting) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *JobPosting) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobPosting) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *JobPosting) GetExperienceRequirement() string {
	if x != nil {
		return x.ExperienceRequirement
	}
	return ""
}

func (x *JobPosting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobPosting) GetResponsibilities() string {
	if x != nil {
		return x.Responsibilities
	}
	return ""
}

func (x *JobPosting) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *JobPosting) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *JobPosting) GetJobTech() []string {
	if x != nil {
		return x.JobTech
	}
	return nil
}

func (x *JobPosting) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x1aCreateTrackingJDTOSRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\"\n" +
	"\rtime_on_sight\x18\x02 \x01(\x05R\vtimeOnSight\"\x1a\n" +
	"\x18CreateTrackingJDTOSReply\"'\n" +
	"\x0eSaveJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"B\n" +
	"\fSaveJobReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x10UnsaveJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"D\n" +
	"\x0eUnsaveJobReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x13GetSavedJobsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x11GetSavedJobsReply\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.api.user.v1.JobPostingR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa1\x04\n" +
	"\n" +
	"JobPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\a \x01(\x01R\tsalaryMax\x12'\n" +
	"\x0fsalary_currency\x18\b \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x1b\n" +
	"\tposted_at\x18\n" +
	" \x01(\tR\bpostedAt\x125\n" +
	"\x16experience_requirement\x18\v \x01(\tR\x15experienceRequirement\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\r \x01(\tR\x10responsibilities\x12\"\n" +
	"\frequirements\x18\x0e \x01(\tR\frequirements\x12\x1a\n" +
	"\bbenefits\x18\x0f \x01(\tR\bbenefits\x12\x19\n" +
	"\bjob_tech\x18\x10 \x03(\tR\ajobTech\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt2\xe8\x03\n" +
	"\x04User\x12\x8f\x01\n" +
	"\x13CreateTrackingJDTOS\x12'.api.user.v1.CreateTrackingJDTOSRequest\x1a%.api.user.v1.CreateTrackingJDTOSReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/users/tracking/jd_tos\x12f\n" +
	"\aSaveJob\x12\x1b.api.user.v1.SaveJobRequest\x1a\x19.api.user.v1.SaveJobReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/users/saved-jobs\x12r\n" +
	"\tUnsaveJob\x12\x1d.api.user.v1.UnsaveJobRequest\x1a\x1b.api.user.v1.UnsaveJobReply\")\x82\xd3\xe4\x93\x02#*!/api/v1/users/saved-jobs/{job_id}\x12r\n" +
	"\fGetSavedJobs\x12 .api.user.v1.GetSavedJobsRequest\x1a\x1e.api.user.v1.GetSavedJobsReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/users/saved-jobsB(\n" +
	"\vapi.user.v1P\x01Z\x17JobblyBE/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_v1_user_proto_goTypes = []any{
	(*CreateTrackingJDTOSRequest)(nil), // 0: api.user.v1.CreateTrackingJDTOSRequest
	(*CreateTrackingJDTOSReply)(nil),   // 1: api.user.v1.CreateTrackingJDTOSReply
	(*SaveJobRequest)(nil),             // 2: api.user.v1.SaveJobRequest
	(*SaveJobReply)(nil),               // 3: api.user.v1.SaveJobReply
	(*UnsaveJobRequest)(nil),           // 4: api.user.v1.UnsaveJobRequest
	(*UnsaveJobReply)(nil),             // 5: api.user.v1.UnsaveJobReply
	(*GetSavedJobsRequest)(nil),        // 6: api.user.v1.GetSavedJobsRequest
	(*GetSavedJobsReply)(nil),          // 7: api.user.v1.GetSavedJobsReply
	(*JobPosting)(nil),                 // 8: api.user.v1.JobPosting
}
var file_user_v1_user_proto_depIdxs = []int32{
	8, // 0: api.user.v1.GetSavedJobsReply.jobs:type_name -> api.user.v1.JobPosting
	0, // 1: api.user.v1.User.CreateTrackingJDTOS:input_type -> api.user.v1.CreateTrackingJDTOSRequest
	2, // 2: api.user.v1.User.SaveJob:input_type -> api.user.v1.SaveJobRequest
	4, // 3: api.user.v1.User.UnsaveJob:input_type -> api.user.v1.UnsaveJobRequest
	6, // 4: api.user.v1.User.GetSavedJobs:input_type -> api.user.v1.GetSavedJobsRequest
	1, // 5: api.user.v1.User.CreateTrackingJDTOS:output_type -> api.user.v1.CreateTrackingJDTOSReply
	3, // 6: api.user.v1.User.SaveJob:output_type -> api.user.v1.SaveJobReply
	5, // 7: api.user.v1.User.UnsaveJob:output_type -> api.user.v1.UnsaveJobReply
	7, // 8: api.user.v1.User.GetSavedJobs:output_type -> api.user.v1.GetSavedJobsReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
