// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"JobblyBE/internal/biz"
	"JobblyBE/internal/conf"
	"JobblyBE/internal/data"
	"JobblyBE/internal/server"
	"JobblyBE/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	authUseCase := biz.NewAuthUsecase(userRepo, logger)
	string2 := confServer.JwtSecret
	authService := service.NewAuthService(authUseCase, string2, logger)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	jobPostingRepo := data.NewJobPostingRepo(dataData, logger)
	companyRepo := data.NewCompanyRepo(dataData, logger)
	jobPostingUseCase := biz.NewJobPostingUseCase(jobPostingRepo, companyRepo, logger)
	userTrackingRepo := data.NewUserTrackingRepo(dataData, logger)
	userTrackingUseCase := biz.NewUserTrackingUseCase(userTrackingRepo, logger)
	jobPostingService := service.NewJobPostingService(jobPostingUseCase, userTrackingUseCase)
	companyUseCase := biz.NewCompanyUseCase(companyRepo, logger)
	companyService := service.NewCompanyService(companyUseCase)
	resumeRepo := data.NewResumeRepo(dataData, logger)
	resumeUseCase := biz.NewResumeUseCase(resumeRepo, logger)
	resumeService := service.NewResumeService(resumeUseCase)
	httpServer := server.NewHTTPServer(confServer, confData, authService, jobPostingService, companyService, resumeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
