// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: job/v1/job.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Industry      string                 `protobuf:"bytes,6,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize   string                 `protobuf:"bytes,7,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	FoundedYear   string                 `protobuf:"bytes,9,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyInfo) Reset() {
	*x = CompanyInfo{}
	mi := &file_job_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfo) ProtoMessage() {}

func (x *CompanyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfo.ProtoReflect.Descriptor instead.
func (*CompanyInfo) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanyInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CompanyInfo) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CompanyInfo) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CompanyInfo) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *CompanyInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CompanyInfo) GetFoundedYear() string {
	if x != nil {
		return x.FoundedYear
	}
	return ""
}

type JobPostingReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId             string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Company               *CompanyInfo           `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Level                 string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`                    // ENTRY, JUNIOR, MID, SENIOR, LEAD
	JobType               string                 `protobuf:"bytes,6,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"` // FULL_TIME, PART_TIME, CONTRACT, INTERNSHIP
	SalaryMin             float64                `protobuf:"fixed64,7,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax             float64                `protobuf:"fixed64,8,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	SalaryCurrency        string                 `protobuf:"bytes,9,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"` // USD, VND, etc
	Location              string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	PostedAt              string                 `protobuf:"bytes,11,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	ExperienceRequirement string                 `protobuf:"bytes,12,opt,name=experience_requirement,json=experienceRequirement,proto3" json:"experience_requirement,omitempty"`
	Description           string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities      string                 `protobuf:"bytes,14,opt,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Requirements          string                 `protobuf:"bytes,15,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Benefits              string                 `protobuf:"bytes,16,opt,name=benefits,proto3" json:"benefits,omitempty"`
	JobTech               []string               `protobuf:"bytes,17,rep,name=job_tech,json=jobTech,proto3" json:"job_tech,omitempty"` // Technologies/skills required
	CreatedAt             string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JobPostingReply) Reset() {
	*x = JobPostingReply{}
	mi := &file_job_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPostingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPostingReply) ProtoMessage() {}

func (x *JobPostingReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPostingReply.ProtoReflect.Descriptor instead.
func (*JobPostingReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobPostingReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobPostingReply) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *JobPostingReply) GetCompany() *CompanyInfo {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *JobPostingReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobPostingReply) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *JobPostingReply) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobPostingReply) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *JobPostingReply) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *JobPostingReply) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *JobPostingReply) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobPostingReply) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *JobPostingReply) GetExperienceRequirement() string {
	if x != nil {
		return x.ExperienceRequirement
	}
	return ""
}

func (x *JobPostingReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobPostingReply) GetResponsibilities() string {
	if x != nil {
		return x.Responsibilities
	}
	return ""
}

func (x *JobPostingReply) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *JobPostingReply) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *JobPostingReply) GetJobTech() []string {
	if x != nil {
		return x.JobTech
	}
	return nil
}

func (x *JobPostingReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateJobPostingRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CompanyId             string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Level                 string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	JobType               string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	SalaryMin             float64                `protobuf:"fixed64,5,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax             float64                `protobuf:"fixed64,6,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	SalaryCurrency        string                 `protobuf:"bytes,7,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Location              string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	PostedAt              string                 `protobuf:"bytes,9,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"` // ISO 8601 date string
	ExperienceRequirement string                 `protobuf:"bytes,10,opt,name=experience_requirement,json=experienceRequirement,proto3" json:"experience_requirement,omitempty"`
	Description           string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities      string                 `protobuf:"bytes,12,opt,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Requirements          string                 `protobuf:"bytes,13,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Benefits              string                 `protobuf:"bytes,14,opt,name=benefits,proto3" json:"benefits,omitempty"`
	JobTech               []string               `protobuf:"bytes,15,rep,name=job_tech,json=jobTech,proto3" json:"job_tech,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateJobPostingRequest) Reset() {
	*x = CreateJobPostingRequest{}
	mi := &file_job_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobPostingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobPostingRequest) ProtoMessage() {}

func (x *CreateJobPostingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobPostingRequest.ProtoReflect.Descriptor instead.
func (*CreateJobPostingRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobPostingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateJobPostingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobPostingRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateJobPostingRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobPostingRequest) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *CreateJobPostingRequest) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *CreateJobPostingRequest) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *CreateJobPostingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateJobPostingRequest) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *CreateJobPostingRequest) GetExperienceRequirement() string {
	if x != nil {
		return x.ExperienceRequirement
	}
	return ""
}

func (x *CreateJobPostingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobPostingRequest) GetResponsibilities() string {
	if x != nil {
		return x.Responsibilities
	}
	return ""
}

func (x *CreateJobPostingRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *CreateJobPostingRequest) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *CreateJobPostingRequest) GetJobTech() []string {
	if x != nil {
		return x.JobTech
	}
	return nil
}

type UpdateJobPostingRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Level                 string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	JobType               string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	SalaryMin             float64                `protobuf:"fixed64,5,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax             float64                `protobuf:"fixed64,6,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	SalaryCurrency        string                 `protobuf:"bytes,7,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Location              string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	PostedAt              string                 `protobuf:"bytes,9,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	ExperienceRequirement string                 `protobuf:"bytes,10,opt,name=experience_requirement,json=experienceRequirement,proto3" json:"experience_requirement,omitempty"`
	Description           string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities      string                 `protobuf:"bytes,12,opt,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Requirements          string                 `protobuf:"bytes,13,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Benefits              string                 `protobuf:"bytes,14,opt,name=benefits,proto3" json:"benefits,omitempty"`
	JobTech               []string               `protobuf:"bytes,15,rep,name=job_tech,json=jobTech,proto3" json:"job_tech,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateJobPostingRequest) Reset() {
	*x = UpdateJobPostingRequest{}
	mi := &file_job_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobPostingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobPostingRequest) ProtoMessage() {}

func (x *UpdateJobPostingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobPostingRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobPostingRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateJobPostingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *UpdateJobPostingRequest) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *UpdateJobPostingRequest) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetExperienceRequirement() string {
	if x != nil {
		return x.ExperienceRequirement
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetResponsibilities() string {
	if x != nil {
		return x.Responsibilities
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *UpdateJobPostingRequest) GetJobTech() []string {
	if x != nil {
		return x.JobTech
	}
	return nil
}

type DeleteJobPostingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobPostingRequest) Reset() {
	*x = DeleteJobPostingRequest{}
	mi := &file_job_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobPostingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobPostingRequest) ProtoMessage() {}

func (x *DeleteJobPostingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobPostingRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobPostingRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteJobPostingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJobPostingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobPostingReply) Reset() {
	*x = DeleteJobPostingReply{}
	mi := &file_job_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobPostingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobPostingReply) ProtoMessage() {}

func (x *DeleteJobPostingReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobPostingReply.ProtoReflect.Descriptor instead.
func (*DeleteJobPostingReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteJobPostingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobPostingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobPostingRequest) Reset() {
	*x = GetJobPostingRequest{}
	mi := &file_job_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobPostingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobPostingRequest) ProtoMessage() {}

func (x *GetJobPostingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobPostingRequest.ProtoReflect.Descriptor instead.
func (*GetJobPostingRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobPostingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListJobPostingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Filter by company
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                    // Filter by location
	JobType       string                 `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`       // Filter by job type
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`                          // Filter by level
	Keyword       string                 `protobuf:"bytes,7,opt,name=keyword,proto3" json:"keyword,omitempty"`                      // Search in title and description
	JobTech       []string               `protobuf:"bytes,8,rep,name=job_tech,json=jobTech,proto3" json:"job_tech,omitempty"`       // Filter by technologies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobPostingsRequest) Reset() {
	*x = ListJobPostingsRequest{}
	mi := &file_job_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobPostingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobPostingsRequest) ProtoMessage() {}

func (x *ListJobPostingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobPostingsRequest.ProtoReflect.Descriptor instead.
func (*ListJobPostingsRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobPostingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobPostingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobPostingsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListJobPostingsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListJobPostingsRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListJobPostingsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ListJobPostingsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListJobPostingsRequest) GetJobTech() []string {
	if x != nil {
		return x.JobTech
	}
	return nil
}

type ListJobPostingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobPostingReply     `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobPostingsReply) Reset() {
	*x = ListJobPostingsReply{}
	mi := &file_job_v1_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobPostingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobPostingsReply) ProtoMessage() {}

func (x *ListJobPostingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobPostingsReply.ProtoReflect.Descriptor instead.
func (*ListJobPostingsReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *ListJobPostingsReply) GetJobs() []*JobPostingReply {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobPostingsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobPostingsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobPostingsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CompanyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Industry      string                 `protobuf:"bytes,6,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize   string                 `protobuf:"bytes,7,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	FoundedYear   string                 `protobuf:"bytes,9,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyReply) Reset() {
	*x = CompanyReply{}
	mi := &file_job_v1_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyReply) ProtoMessage() {}

func (x *CompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyReply.ProtoReflect.Descriptor instead.
func (*CompanyReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{9}
}

func (x *CompanyReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanyReply) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CompanyReply) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CompanyReply) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CompanyReply) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *CompanyReply) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CompanyReply) GetFoundedYear() string {
	if x != nil {
		return x.FoundedYear
	}
	return ""
}

type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Industry      string                 `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize   string                 `protobuf:"bytes,6,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FoundedYear   string                 `protobuf:"bytes,8,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_job_v1_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCompanyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCompanyRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateCompanyRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CreateCompanyRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CreateCompanyRequest) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *CreateCompanyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateCompanyRequest) GetFoundedYear() string {
	if x != nil {
		return x.FoundedYear
	}
	return ""
}

type UpdateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Industry      string                 `protobuf:"bytes,6,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize   string                 `protobuf:"bytes,7,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	FoundedYear   string                 `protobuf:"bytes,9,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyRequest) Reset() {
	*x = UpdateCompanyRequest{}
	mi := &file_job_v1_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyRequest) ProtoMessage() {}

func (x *UpdateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCompanyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCompanyRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateCompanyRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpdateCompanyRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *UpdateCompanyRequest) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *UpdateCompanyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCompanyRequest) GetFoundedYear() string {
	if x != nil {
		return x.FoundedYear
	}
	return ""
}

type DeleteCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyRequest) Reset() {
	*x = DeleteCompanyRequest{}
	mi := &file_job_v1_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyRequest) ProtoMessage() {}

func (x *DeleteCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCompanyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyReply) Reset() {
	*x = DeleteCompanyReply{}
	mi := &file_job_v1_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyReply) ProtoMessage() {}

func (x *DeleteCompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyReply.ProtoReflect.Descriptor instead.
func (*DeleteCompanyReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCompanyReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_job_v1_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{14}
}

func (x *GetCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Industry      string                 `protobuf:"bytes,3,opt,name=industry,proto3" json:"industry,omitempty"` // Filter by industry
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"` // Filter by location
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`   // Search in name and description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesRequest) Reset() {
	*x = ListCompaniesRequest{}
	mi := &file_job_v1_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesRequest) ProtoMessage() {}

func (x *ListCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesRequest.ProtoReflect.Descriptor instead.
func (*ListCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{15}
}

func (x *ListCompaniesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCompaniesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCompaniesRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *ListCompaniesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListCompaniesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListCompaniesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*CompanyReply        `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesReply) Reset() {
	*x = ListCompaniesReply{}
	mi := &file_job_v1_job_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesReply) ProtoMessage() {}

func (x *ListCompaniesReply) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesReply.ProtoReflect.Descriptor instead.
func (*ListCompaniesReply) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{16}
}

func (x *ListCompaniesReply) GetCompanies() []*CompanyReply {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *ListCompaniesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCompaniesReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCompaniesReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_job_v1_job_proto protoreflect.FileDescriptor

const file_job_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x10job/v1/job.proto\x12\n" +
	"api.job.v1\x1a\x1cgoogle/api/annotations.proto\"\x86\x02\n" +
	"\vCompanyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12\x1a\n" +
	"\bindustry\x18\x06 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\a \x01(\tR\vcompanySize\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12!\n" +
	"\ffounded_year\x18\t \x01(\tR\vfoundedYear\"\xd9\x04\n" +
	"\x0fJobPostingReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x121\n" +
	"\acompany\x18\x03 \x01(\v2\x17.api.job.v1.CompanyInfoR\acompany\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x19\n" +
	"\bjob_type\x18\x06 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"salary_min\x18\a \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\b \x01(\x01R\tsalaryMax\x12'\n" +
	"\x0fsalary_currency\x18\t \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x1b\n" +
	"\tposted_at\x18\v \x01(\tR\bpostedAt\x125\n" +
	"\x16experience_requirement\x18\f \x01(\tR\x15experienceRequirement\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\x0e \x01(\tR\x10responsibilities\x12\"\n" +
	"\frequirements\x18\x0f \x01(\tR\frequirements\x12\x1a\n" +
	"\bbenefits\x18\x10 \x01(\tR\bbenefits\x12\x19\n" +
	"\bjob_tech\x18\x11 \x03(\tR\ajobTech\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\"\xff\x03\n" +
	"\x17CreateJobPostingRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x05 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x06 \x01(\x01R\tsalaryMax\x12'\n" +
	"\x0fsalary_currency\x18\a \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1b\n" +
	"\tposted_at\x18\t \x01(\tR\bpostedAt\x125\n" +
	"\x16experience_requirement\x18\n" +
	" \x01(\tR\x15experienceRequirement\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\f \x01(\tR\x10responsibilities\x12\"\n" +
	"\frequirements\x18\r \x01(\tR\frequirements\x12\x1a\n" +
	"\bbenefits\x18\x0e \x01(\tR\bbenefits\x12\x19\n" +
	"\bjob_tech\x18\x0f \x03(\tR\ajobTech\"\xf0\x03\n" +
	"\x17UpdateJobPostingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x05 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x06 \x01(\x01R\tsalaryMax\x12'\n" +
	"\x0fsalary_currency\x18\a \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1b\n" +
	"\tposted_at\x18\t \x01(\tR\bpostedAt\x125\n" +
	"\x16experience_requirement\x18\n" +
	" \x01(\tR\x15experienceRequirement\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\f \x01(\tR\x10responsibilities\x12\"\n" +
	"\frequirements\x18\r \x01(\tR\frequirements\x12\x1a\n" +
	"\bbenefits\x18\x0e \x01(\tR\bbenefits\x12\x19\n" +
	"\bjob_tech\x18\x0f \x03(\tR\ajobTech\")\n" +
	"\x17DeleteJobPostingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteJobPostingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\x14GetJobPostingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xea\x01\n" +
	"\x16ListJobPostingsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12\x18\n" +
	"\akeyword\x18\a \x01(\tR\akeyword\x12\x19\n" +
	"\bjob_tech\x18\b \x03(\tR\ajobTech\"\x8e\x01\n" +
	"\x14ListJobPostingsReply\x12/\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1b.api.job.v1.JobPostingReplyR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x87\x02\n" +
	"\fCompanyReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12\x1a\n" +
	"\bindustry\x18\x06 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\a \x01(\tR\vcompanySize\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12!\n" +
	"\ffounded_year\x18\t \x01(\tR\vfoundedYear\"\xff\x01\n" +
	"\x14CreateCompanyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\x06 \x01(\tR\vcompanySize\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12!\n" +
	"\ffounded_year\x18\b \x01(\tR\vfoundedYear\"\x8f\x02\n" +
	"\x14UpdateCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12\x1a\n" +
	"\bindustry\x18\x06 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\a \x01(\tR\vcompanySize\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12!\n" +
	"\ffounded_year\x18\t \x01(\tR\vfoundedYear\"&\n" +
	"\x14DeleteCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteCompanyReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\x14ListCompaniesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bindustry\x18\x03 \x01(\tR\bindustry\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"\x93\x01\n" +
	"\x12ListCompaniesReply\x126\n" +
	"\tcompanies\x18\x01 \x03(\v2\x18.api.job.v1.CompanyReplyR\tcompanies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xc0\x04\n" +
	"\n" +
	"JobPosting\x12m\n" +
	"\x10CreateJobPosting\x12#.api.job.v1.CreateJobPostingRequest\x1a\x1b.api.job.v1.JobPostingReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/jobs\x12r\n" +
	"\x10UpdateJobPosting\x12#.api.job.v1.UpdateJobPostingRequest\x1a\x1b.api.job.v1.JobPostingReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/jobs/{id}\x12u\n" +
	"\x10DeleteJobPosting\x12#.api.job.v1.DeleteJobPostingRequest\x1a!.api.job.v1.DeleteJobPostingReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/jobs/{id}\x12i\n" +
	"\rGetJobPosting\x12 .api.job.v1.GetJobPostingRequest\x1a\x1b.api.job.v1.JobPostingReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/jobs/{id}\x12m\n" +
	"\x0fListJobPostings\x12\".api.job.v1.ListJobPostingsRequest\x1a .api.job.v1.ListJobPostingsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs2\xac\x04\n" +
	"\aCompany\x12i\n" +
	"\rCreateCompany\x12 .api.job.v1.CreateCompanyRequest\x1a\x18.api.job.v1.CompanyReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/companies\x12n\n" +
	"\rUpdateCompany\x12 .api.job.v1.UpdateCompanyRequest\x1a\x18.api.job.v1.CompanyReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/companies/{id}\x12q\n" +
	"\rDeleteCompany\x12 .api.job.v1.DeleteCompanyRequest\x1a\x1e.api.job.v1.DeleteCompanyReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/companies/{id}\x12e\n" +
	"\n" +
	"GetCompany\x12\x1d.api.job.v1.GetCompanyRequest\x1a\x18.api.job.v1.CompanyReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/companies/{id}\x12l\n" +
	"\rListCompanies\x12 .api.job.v1.ListCompaniesRequest\x1a\x1e.api.job.v1.ListCompaniesReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/companiesB&\n" +
	"\n" +
	"api.job.v1P\x01Z\x16JobblyBE/api/job/v1;v1b\x06proto3"

var (
	file_job_v1_job_proto_rawDescOnce sync.Once
	file_job_v1_job_proto_rawDescData []byte
)

func file_job_v1_job_proto_rawDescGZIP() []byte {
	file_job_v1_job_proto_rawDescOnce.Do(func() {
		file_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)))
	})
	return file_job_v1_job_proto_rawDescData
}

var file_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_job_v1_job_proto_goTypes = []any{
	(*CompanyInfo)(nil),             // 0: api.job.v1.CompanyInfo
	(*JobPostingReply)(nil),         // 1: api.job.v1.JobPostingReply
	(*CreateJobPostingRequest)(nil), // 2: api.job.v1.CreateJobPostingRequest
	(*UpdateJobPostingRequest)(nil), // 3: api.job.v1.UpdateJobPostingRequest
	(*DeleteJobPostingRequest)(nil), // 4: api.job.v1.DeleteJobPostingRequest
	(*DeleteJobPostingReply)(nil),   // 5: api.job.v1.DeleteJobPostingReply
	(*GetJobPostingRequest)(nil),    // 6: api.job.v1.GetJobPostingRequest
	(*ListJobPostingsRequest)(nil),  // 7: api.job.v1.ListJobPostingsRequest
	(*ListJobPostingsReply)(nil),    // 8: api.job.v1.ListJobPostingsReply
	(*CompanyReply)(nil),            // 9: api.job.v1.CompanyReply
	(*CreateCompanyRequest)(nil),    // 10: api.job.v1.CreateCompanyRequest
	(*UpdateCompanyRequest)(nil),    // 11: api.job.v1.UpdateCompanyRequest
	(*DeleteCompanyRequest)(nil),    // 12: api.job.v1.DeleteCompanyRequest
	(*DeleteCompanyReply)(nil),      // 13: api.job.v1.DeleteCompanyReply
	(*GetCompanyRequest)(nil),       // 14: api.job.v1.GetCompanyRequest
	(*ListCompaniesRequest)(nil),    // 15: api.job.v1.ListCompaniesRequest
	(*ListCompaniesReply)(nil),      // 16: api.job.v1.ListCompaniesReply
}
var file_job_v1_job_proto_depIdxs = []int32{
	0,  // 0: api.job.v1.JobPostingReply.company:type_name -> api.job.v1.CompanyInfo
	1,  // 1: api.job.v1.ListJobPostingsReply.jobs:type_name -> api.job.v1.JobPostingReply
	9,  // 2: api.job.v1.ListCompaniesReply.companies:type_name -> api.job.v1.CompanyReply
	2,  // 3: api.job.v1.JobPosting.CreateJobPosting:input_type -> api.job.v1.CreateJobPostingRequest
	3,  // 4: api.job.v1.JobPosting.UpdateJobPosting:input_type -> api.job.v1.UpdateJobPostingRequest
	4,  // 5: api.job.v1.JobPosting.DeleteJobPosting:input_type -> api.job.v1.DeleteJobPostingRequest
	6,  // 6: api.job.v1.JobPosting.GetJobPosting:input_type -> api.job.v1.GetJobPostingRequest
	7,  // 7: api.job.v1.JobPosting.ListJobPostings:input_type -> api.job.v1.ListJobPostingsRequest
	10, // 8: api.job.v1.Company.CreateCompany:input_type -> api.job.v1.CreateCompanyRequest
	11, // 9: api.job.v1.Company.UpdateCompany:input_type -> api.job.v1.UpdateCompanyRequest
	12, // 10: api.job.v1.Company.DeleteCompany:input_type -> api.job.v1.DeleteCompanyRequest
	14, // 11: api.job.v1.Company.GetCompany:input_type -> api.job.v1.GetCompanyRequest
	15, // 12: api.job.v1.Company.ListCompanies:input_type -> api.job.v1.ListCompaniesRequest
	1,  // 13: api.job.v1.JobPosting.CreateJobPosting:output_type -> api.job.v1.JobPostingReply
	1,  // 14: api.job.v1.JobPosting.UpdateJobPosting:output_type -> api.job.v1.JobPostingReply
	5,  // 15: api.job.v1.JobPosting.DeleteJobPosting:output_type -> api.job.v1.DeleteJobPostingReply
	1,  // 16: api.job.v1.JobPosting.GetJobPosting:output_type -> api.job.v1.JobPostingReply
	8,  // 17: api.job.v1.JobPosting.ListJobPostings:output_type -> api.job.v1.ListJobPostingsReply
	9,  // 18: api.job.v1.Company.CreateCompany:output_type -> api.job.v1.CompanyReply
	9,  // 19: api.job.v1.Company.UpdateCompany:output_type -> api.job.v1.CompanyReply
	13, // 20: api.job.v1.Company.DeleteCompany:output_type -> api.job.v1.DeleteCompanyReply
	9,  // 21: api.job.v1.Company.GetCompany:output_type -> api.job.v1.CompanyReply
	16, // 22: api.job.v1.Company.ListCompanies:output_type -> api.job.v1.ListCompaniesReply
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_job_v1_job_proto_init() }
func file_job_v1_job_proto_init() {
	if File_job_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_job_v1_job_proto_goTypes,
		DependencyIndexes: file_job_v1_job_proto_depIdxs,
		MessageInfos:      file_job_v1_job_proto_msgTypes,
	}.Build()
	File_job_v1_job_proto = out.File
	file_job_v1_job_proto_goTypes = nil
	file_job_v1_job_proto_depIdxs = nil
}
