// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: job/v1/job.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobPosting_CreateJobPosting_FullMethodName = "/api.job.v1.JobPosting/CreateJobPosting"
	JobPosting_UpdateJobPosting_FullMethodName = "/api.job.v1.JobPosting/UpdateJobPosting"
	JobPosting_DeleteJobPosting_FullMethodName = "/api.job.v1.JobPosting/DeleteJobPosting"
	JobPosting_GetJobPosting_FullMethodName    = "/api.job.v1.JobPosting/GetJobPosting"
	JobPosting_ListJobPostings_FullMethodName  = "/api.job.v1.JobPosting/ListJobPostings"
)

// JobPostingClient is the client API for JobPosting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Job Posting Service
type JobPostingClient interface {
	// Create a new job posting
	CreateJobPosting(ctx context.Context, in *CreateJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error)
	// Update an existing job posting
	UpdateJobPosting(ctx context.Context, in *UpdateJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error)
	// Delete a job posting
	DeleteJobPosting(ctx context.Context, in *DeleteJobPostingRequest, opts ...grpc.CallOption) (*DeleteJobPostingReply, error)
	// Get a single job posting by ID
	GetJobPosting(ctx context.Context, in *GetJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error)
	// List all job postings with pagination and filters
	ListJobPostings(ctx context.Context, in *ListJobPostingsRequest, opts ...grpc.CallOption) (*ListJobPostingsReply, error)
}

type jobPostingClient struct {
	cc grpc.ClientConnInterface
}

func NewJobPostingClient(cc grpc.ClientConnInterface) JobPostingClient {
	return &jobPostingClient{cc}
}

func (c *jobPostingClient) CreateJobPosting(ctx context.Context, in *CreateJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobPostingReply)
	err := c.cc.Invoke(ctx, JobPosting_CreateJobPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobPostingClient) UpdateJobPosting(ctx context.Context, in *UpdateJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobPostingReply)
	err := c.cc.Invoke(ctx, JobPosting_UpdateJobPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobPostingClient) DeleteJobPosting(ctx context.Context, in *DeleteJobPostingRequest, opts ...grpc.CallOption) (*DeleteJobPostingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobPostingReply)
	err := c.cc.Invoke(ctx, JobPosting_DeleteJobPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobPostingClient) GetJobPosting(ctx context.Context, in *GetJobPostingRequest, opts ...grpc.CallOption) (*JobPostingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobPostingReply)
	err := c.cc.Invoke(ctx, JobPosting_GetJobPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobPostingClient) ListJobPostings(ctx context.Context, in *ListJobPostingsRequest, opts ...grpc.CallOption) (*ListJobPostingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobPostingsReply)
	err := c.cc.Invoke(ctx, JobPosting_ListJobPostings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobPostingServer is the server API for JobPosting service.
// All implementations must embed UnimplementedJobPostingServer
// for forward compatibility.
//
// Job Posting Service
type JobPostingServer interface {
	// Create a new job posting
	CreateJobPosting(context.Context, *CreateJobPostingRequest) (*JobPostingReply, error)
	// Update an existing job posting
	UpdateJobPosting(context.Context, *UpdateJobPostingRequest) (*JobPostingReply, error)
	// Delete a job posting
	DeleteJobPosting(context.Context, *DeleteJobPostingRequest) (*DeleteJobPostingReply, error)
	// Get a single job posting by ID
	GetJobPosting(context.Context, *GetJobPostingRequest) (*JobPostingReply, error)
	// List all job postings with pagination and filters
	ListJobPostings(context.Context, *ListJobPostingsRequest) (*ListJobPostingsReply, error)
	mustEmbedUnimplementedJobPostingServer()
}

// UnimplementedJobPostingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobPostingServer struct{}

func (UnimplementedJobPostingServer) CreateJobPosting(context.Context, *CreateJobPostingRequest) (*JobPostingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobPosting not implemented")
}
func (UnimplementedJobPostingServer) UpdateJobPosting(context.Context, *UpdateJobPostingRequest) (*JobPostingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobPosting not implemented")
}
func (UnimplementedJobPostingServer) DeleteJobPosting(context.Context, *DeleteJobPostingRequest) (*DeleteJobPostingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobPosting not implemented")
}
func (UnimplementedJobPostingServer) GetJobPosting(context.Context, *GetJobPostingRequest) (*JobPostingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobPosting not implemented")
}
func (UnimplementedJobPostingServer) ListJobPostings(context.Context, *ListJobPostingsRequest) (*ListJobPostingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobPostings not implemented")
}
func (UnimplementedJobPostingServer) mustEmbedUnimplementedJobPostingServer() {}
func (UnimplementedJobPostingServer) testEmbeddedByValue()                    {}

// UnsafeJobPostingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobPostingServer will
// result in compilation errors.
type UnsafeJobPostingServer interface {
	mustEmbedUnimplementedJobPostingServer()
}

func RegisterJobPostingServer(s grpc.ServiceRegistrar, srv JobPostingServer) {
	// If the following call pancis, it indicates UnimplementedJobPostingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobPosting_ServiceDesc, srv)
}

func _JobPosting_CreateJobPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobPostingServer).CreateJobPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobPosting_CreateJobPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobPostingServer).CreateJobPosting(ctx, req.(*CreateJobPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobPosting_UpdateJobPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobPostingServer).UpdateJobPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobPosting_UpdateJobPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobPostingServer).UpdateJobPosting(ctx, req.(*UpdateJobPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobPosting_DeleteJobPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobPostingServer).DeleteJobPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobPosting_DeleteJobPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobPostingServer).DeleteJobPosting(ctx, req.(*DeleteJobPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobPosting_GetJobPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobPostingServer).GetJobPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobPosting_GetJobPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobPostingServer).GetJobPosting(ctx, req.(*GetJobPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobPosting_ListJobPostings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobPostingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobPostingServer).ListJobPostings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobPosting_ListJobPostings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobPostingServer).ListJobPostings(ctx, req.(*ListJobPostingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobPosting_ServiceDesc is the grpc.ServiceDesc for JobPosting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobPosting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.job.v1.JobPosting",
	HandlerType: (*JobPostingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJobPosting",
			Handler:    _JobPosting_CreateJobPosting_Handler,
		},
		{
			MethodName: "UpdateJobPosting",
			Handler:    _JobPosting_UpdateJobPosting_Handler,
		},
		{
			MethodName: "DeleteJobPosting",
			Handler:    _JobPosting_DeleteJobPosting_Handler,
		},
		{
			MethodName: "GetJobPosting",
			Handler:    _JobPosting_GetJobPosting_Handler,
		},
		{
			MethodName: "ListJobPostings",
			Handler:    _JobPosting_ListJobPostings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job/v1/job.proto",
}

const (
	Company_CreateCompany_FullMethodName = "/api.job.v1.Company/CreateCompany"
	Company_UpdateCompany_FullMethodName = "/api.job.v1.Company/UpdateCompany"
	Company_DeleteCompany_FullMethodName = "/api.job.v1.Company/DeleteCompany"
	Company_GetCompany_FullMethodName    = "/api.job.v1.Company/GetCompany"
	Company_ListCompanies_FullMethodName = "/api.job.v1.Company/ListCompanies"
)

// CompanyClient is the client API for Company service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Company Service
type CompanyClient interface {
	// Create a new company
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error)
	// Update an existing company
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error)
	// Delete a company
	DeleteCompany(ctx context.Context, in *DeleteCompanyRequest, opts ...grpc.CallOption) (*DeleteCompanyReply, error)
	// Get a single company by ID
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error)
	// List all companies with pagination
	ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesReply, error)
}

type companyClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyClient(cc grpc.ClientConnInterface) CompanyClient {
	return &companyClient{cc}
}

func (c *companyClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyReply)
	err := c.cc.Invoke(ctx, Company_CreateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyReply)
	err := c.cc.Invoke(ctx, Company_UpdateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) DeleteCompany(ctx context.Context, in *DeleteCompanyRequest, opts ...grpc.CallOption) (*DeleteCompanyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCompanyReply)
	err := c.cc.Invoke(ctx, Company_DeleteCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyReply)
	err := c.cc.Invoke(ctx, Company_GetCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCompaniesReply)
	err := c.cc.Invoke(ctx, Company_ListCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyServer is the server API for Company service.
// All implementations must embed UnimplementedCompanyServer
// for forward compatibility.
//
// Company Service
type CompanyServer interface {
	// Create a new company
	CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyReply, error)
	// Update an existing company
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyReply, error)
	// Delete a company
	DeleteCompany(context.Context, *DeleteCompanyRequest) (*DeleteCompanyReply, error)
	// Get a single company by ID
	GetCompany(context.Context, *GetCompanyRequest) (*CompanyReply, error)
	// List all companies with pagination
	ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesReply, error)
	mustEmbedUnimplementedCompanyServer()
}

// UnimplementedCompanyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompanyServer struct{}

func (UnimplementedCompanyServer) CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}
func (UnimplementedCompanyServer) UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (UnimplementedCompanyServer) DeleteCompany(context.Context, *DeleteCompanyRequest) (*DeleteCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompany not implemented")
}
func (UnimplementedCompanyServer) GetCompany(context.Context, *GetCompanyRequest) (*CompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (UnimplementedCompanyServer) ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCompanies not implemented")
}
func (UnimplementedCompanyServer) mustEmbedUnimplementedCompanyServer() {}
func (UnimplementedCompanyServer) testEmbeddedByValue()                 {}

// UnsafeCompanyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanyServer will
// result in compilation errors.
type UnsafeCompanyServer interface {
	mustEmbedUnimplementedCompanyServer()
}

func RegisterCompanyServer(s grpc.ServiceRegistrar, srv CompanyServer) {
	// If the following call pancis, it indicates UnimplementedCompanyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Company_ServiceDesc, srv)
}

func _Company_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Company_CreateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Company_UpdateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_DeleteCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).DeleteCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Company_DeleteCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).DeleteCompany(ctx, req.(*DeleteCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Company_GetCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_ListCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).ListCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Company_ListCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).ListCompanies(ctx, req.(*ListCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Company_ServiceDesc is the grpc.ServiceDesc for Company service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Company_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.job.v1.Company",
	HandlerType: (*CompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompany",
			Handler:    _Company_CreateCompany_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _Company_UpdateCompany_Handler,
		},
		{
			MethodName: "DeleteCompany",
			Handler:    _Company_DeleteCompany_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _Company_GetCompany_Handler,
		},
		{
			MethodName: "ListCompanies",
			Handler:    _Company_ListCompanies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job/v1/job.proto",
}
