// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.1
// source: job/v1/job.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationJobPostingCreateJobPosting = "/api.job.v1.JobPosting/CreateJobPosting"
const OperationJobPostingDeleteJobPosting = "/api.job.v1.JobPosting/DeleteJobPosting"
const OperationJobPostingGetJobPosting = "/api.job.v1.JobPosting/GetJobPosting"
const OperationJobPostingListJobPostings = "/api.job.v1.JobPosting/ListJobPostings"
const OperationJobPostingUpdateJobPosting = "/api.job.v1.JobPosting/UpdateJobPosting"

type JobPostingHTTPServer interface {
	// CreateJobPosting Create a new job posting
	CreateJobPosting(context.Context, *CreateJobPostingRequest) (*JobPostingReply, error)
	// DeleteJobPosting Delete a job posting
	DeleteJobPosting(context.Context, *DeleteJobPostingRequest) (*DeleteJobPostingReply, error)
	// GetJobPosting Get a single job posting by ID
	GetJobPosting(context.Context, *GetJobPostingRequest) (*JobPostingReply, error)
	// ListJobPostings List all job postings with pagination and filters
	ListJobPostings(context.Context, *ListJobPostingsRequest) (*ListJobPostingsReply, error)
	// UpdateJobPosting Update an existing job posting
	UpdateJobPosting(context.Context, *UpdateJobPostingRequest) (*JobPostingReply, error)
}

func RegisterJobPostingHTTPServer(s *http.Server, srv JobPostingHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/jobs", _JobPosting_CreateJobPosting0_HTTP_Handler(srv))
	r.PUT("/api/v1/jobs/{id}", _JobPosting_UpdateJobPosting0_HTTP_Handler(srv))
	r.DELETE("/api/v1/jobs/{id}", _JobPosting_DeleteJobPosting0_HTTP_Handler(srv))
	r.GET("/api/v1/jobs/{id}", _JobPosting_GetJobPosting0_HTTP_Handler(srv))
	r.GET("/api/v1/jobs", _JobPosting_ListJobPostings0_HTTP_Handler(srv))
}

func _JobPosting_CreateJobPosting0_HTTP_Handler(srv JobPostingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateJobPostingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobPostingCreateJobPosting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateJobPosting(ctx, req.(*CreateJobPostingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobPostingReply)
		return ctx.Result(200, reply)
	}
}

func _JobPosting_UpdateJobPosting0_HTTP_Handler(srv JobPostingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateJobPostingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobPostingUpdateJobPosting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateJobPosting(ctx, req.(*UpdateJobPostingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobPostingReply)
		return ctx.Result(200, reply)
	}
}

func _JobPosting_DeleteJobPosting0_HTTP_Handler(srv JobPostingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteJobPostingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobPostingDeleteJobPosting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteJobPosting(ctx, req.(*DeleteJobPostingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteJobPostingReply)
		return ctx.Result(200, reply)
	}
}

func _JobPosting_GetJobPosting0_HTTP_Handler(srv JobPostingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetJobPostingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobPostingGetJobPosting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetJobPosting(ctx, req.(*GetJobPostingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobPostingReply)
		return ctx.Result(200, reply)
	}
}

func _JobPosting_ListJobPostings0_HTTP_Handler(srv JobPostingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListJobPostingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobPostingListJobPostings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListJobPostings(ctx, req.(*ListJobPostingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListJobPostingsReply)
		return ctx.Result(200, reply)
	}
}

type JobPostingHTTPClient interface {
	// CreateJobPosting Create a new job posting
	CreateJobPosting(ctx context.Context, req *CreateJobPostingRequest, opts ...http.CallOption) (rsp *JobPostingReply, err error)
	// DeleteJobPosting Delete a job posting
	DeleteJobPosting(ctx context.Context, req *DeleteJobPostingRequest, opts ...http.CallOption) (rsp *DeleteJobPostingReply, err error)
	// GetJobPosting Get a single job posting by ID
	GetJobPosting(ctx context.Context, req *GetJobPostingRequest, opts ...http.CallOption) (rsp *JobPostingReply, err error)
	// ListJobPostings List all job postings with pagination and filters
	ListJobPostings(ctx context.Context, req *ListJobPostingsRequest, opts ...http.CallOption) (rsp *ListJobPostingsReply, err error)
	// UpdateJobPosting Update an existing job posting
	UpdateJobPosting(ctx context.Context, req *UpdateJobPostingRequest, opts ...http.CallOption) (rsp *JobPostingReply, err error)
}

type JobPostingHTTPClientImpl struct {
	cc *http.Client
}

func NewJobPostingHTTPClient(client *http.Client) JobPostingHTTPClient {
	return &JobPostingHTTPClientImpl{client}
}

// CreateJobPosting Create a new job posting
func (c *JobPostingHTTPClientImpl) CreateJobPosting(ctx context.Context, in *CreateJobPostingRequest, opts ...http.CallOption) (*JobPostingReply, error) {
	var out JobPostingReply
	pattern := "/api/v1/jobs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobPostingCreateJobPosting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteJobPosting Delete a job posting
func (c *JobPostingHTTPClientImpl) DeleteJobPosting(ctx context.Context, in *DeleteJobPostingRequest, opts ...http.CallOption) (*DeleteJobPostingReply, error) {
	var out DeleteJobPostingReply
	pattern := "/api/v1/jobs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobPostingDeleteJobPosting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetJobPosting Get a single job posting by ID
func (c *JobPostingHTTPClientImpl) GetJobPosting(ctx context.Context, in *GetJobPostingRequest, opts ...http.CallOption) (*JobPostingReply, error) {
	var out JobPostingReply
	pattern := "/api/v1/jobs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobPostingGetJobPosting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListJobPostings List all job postings with pagination and filters
func (c *JobPostingHTTPClientImpl) ListJobPostings(ctx context.Context, in *ListJobPostingsRequest, opts ...http.CallOption) (*ListJobPostingsReply, error) {
	var out ListJobPostingsReply
	pattern := "/api/v1/jobs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobPostingListJobPostings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateJobPosting Update an existing job posting
func (c *JobPostingHTTPClientImpl) UpdateJobPosting(ctx context.Context, in *UpdateJobPostingRequest, opts ...http.CallOption) (*JobPostingReply, error) {
	var out JobPostingReply
	pattern := "/api/v1/jobs/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobPostingUpdateJobPosting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationCompanyCreateCompany = "/api.job.v1.Company/CreateCompany"
const OperationCompanyDeleteCompany = "/api.job.v1.Company/DeleteCompany"
const OperationCompanyGetCompany = "/api.job.v1.Company/GetCompany"
const OperationCompanyListCompanies = "/api.job.v1.Company/ListCompanies"
const OperationCompanyUpdateCompany = "/api.job.v1.Company/UpdateCompany"

type CompanyHTTPServer interface {
	// CreateCompany Create a new company
	CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyReply, error)
	// DeleteCompany Delete a company
	DeleteCompany(context.Context, *DeleteCompanyRequest) (*DeleteCompanyReply, error)
	// GetCompany Get a single company by ID
	GetCompany(context.Context, *GetCompanyRequest) (*CompanyReply, error)
	// ListCompanies List all companies with pagination
	ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesReply, error)
	// UpdateCompany Update an existing company
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyReply, error)
}

func RegisterCompanyHTTPServer(s *http.Server, srv CompanyHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/companies", _Company_CreateCompany0_HTTP_Handler(srv))
	r.PUT("/api/v1/companies/{id}", _Company_UpdateCompany0_HTTP_Handler(srv))
	r.DELETE("/api/v1/companies/{id}", _Company_DeleteCompany0_HTTP_Handler(srv))
	r.GET("/api/v1/companies/{id}", _Company_GetCompany0_HTTP_Handler(srv))
	r.GET("/api/v1/companies", _Company_ListCompanies0_HTTP_Handler(srv))
}

func _Company_CreateCompany0_HTTP_Handler(srv CompanyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCompanyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanyCreateCompany)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCompany(ctx, req.(*CreateCompanyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompanyReply)
		return ctx.Result(200, reply)
	}
}

func _Company_UpdateCompany0_HTTP_Handler(srv CompanyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCompanyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanyUpdateCompany)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCompany(ctx, req.(*UpdateCompanyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompanyReply)
		return ctx.Result(200, reply)
	}
}

func _Company_DeleteCompany0_HTTP_Handler(srv CompanyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCompanyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanyDeleteCompany)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCompany(ctx, req.(*DeleteCompanyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCompanyReply)
		return ctx.Result(200, reply)
	}
}

func _Company_GetCompany0_HTTP_Handler(srv CompanyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCompanyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanyGetCompany)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCompany(ctx, req.(*GetCompanyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompanyReply)
		return ctx.Result(200, reply)
	}
}

func _Company_ListCompanies0_HTTP_Handler(srv CompanyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCompaniesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanyListCompanies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCompanies(ctx, req.(*ListCompaniesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCompaniesReply)
		return ctx.Result(200, reply)
	}
}

type CompanyHTTPClient interface {
	// CreateCompany Create a new company
	CreateCompany(ctx context.Context, req *CreateCompanyRequest, opts ...http.CallOption) (rsp *CompanyReply, err error)
	// DeleteCompany Delete a company
	DeleteCompany(ctx context.Context, req *DeleteCompanyRequest, opts ...http.CallOption) (rsp *DeleteCompanyReply, err error)
	// GetCompany Get a single company by ID
	GetCompany(ctx context.Context, req *GetCompanyRequest, opts ...http.CallOption) (rsp *CompanyReply, err error)
	// ListCompanies List all companies with pagination
	ListCompanies(ctx context.Context, req *ListCompaniesRequest, opts ...http.CallOption) (rsp *ListCompaniesReply, err error)
	// UpdateCompany Update an existing company
	UpdateCompany(ctx context.Context, req *UpdateCompanyRequest, opts ...http.CallOption) (rsp *CompanyReply, err error)
}

type CompanyHTTPClientImpl struct {
	cc *http.Client
}

func NewCompanyHTTPClient(client *http.Client) CompanyHTTPClient {
	return &CompanyHTTPClientImpl{client}
}

// CreateCompany Create a new company
func (c *CompanyHTTPClientImpl) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...http.CallOption) (*CompanyReply, error) {
	var out CompanyReply
	pattern := "/api/v1/companies"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanyCreateCompany))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCompany Delete a company
func (c *CompanyHTTPClientImpl) DeleteCompany(ctx context.Context, in *DeleteCompanyRequest, opts ...http.CallOption) (*DeleteCompanyReply, error) {
	var out DeleteCompanyReply
	pattern := "/api/v1/companies/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanyDeleteCompany))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCompany Get a single company by ID
func (c *CompanyHTTPClientImpl) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...http.CallOption) (*CompanyReply, error) {
	var out CompanyReply
	pattern := "/api/v1/companies/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanyGetCompany))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCompanies List all companies with pagination
func (c *CompanyHTTPClientImpl) ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...http.CallOption) (*ListCompaniesReply, error) {
	var out ListCompaniesReply
	pattern := "/api/v1/companies"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanyListCompanies))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCompany Update an existing company
func (c *CompanyHTTPClientImpl) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...http.CallOption) (*CompanyReply, error) {
	var out CompanyReply
	pattern := "/api/v1/companies/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanyUpdateCompany))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
