// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.1
// source: application/v1/application.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationJobApplicationApplyJob = "/api.application.v1.JobApplication/ApplyJob"
const OperationJobApplicationGetApplication = "/api.application.v1.JobApplication/GetApplication"
const OperationJobApplicationListJobApplications = "/api.application.v1.JobApplication/ListJobApplications"
const OperationJobApplicationListUserApplications = "/api.application.v1.JobApplication/ListUserApplications"
const OperationJobApplicationUpdateApplicationStatus = "/api.application.v1.JobApplication/UpdateApplicationStatus"
const OperationJobApplicationWithdrawApplication = "/api.application.v1.JobApplication/WithdrawApplication"

type JobApplicationHTTPServer interface {
	// ApplyJob Apply for a job
	ApplyJob(context.Context, *ApplyJobRequest) (*JobApplicationReply, error)
	// GetApplication Get application detail
	GetApplication(context.Context, *GetApplicationRequest) (*JobApplicationDetailReply, error)
	// ListJobApplications List applications for a job posting (for HR)
	ListJobApplications(context.Context, *ListJobApplicationsRequest) (*ListApplicationsReply, error)
	// ListUserApplications List applications for a user
	ListUserApplications(context.Context, *ListUserApplicationsRequest) (*ListApplicationsReply, error)
	// UpdateApplicationStatus Update application status (for HR)
	UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*JobApplicationReply, error)
	// WithdrawApplication Withdraw application (for user)
	WithdrawApplication(context.Context, *WithdrawApplicationRequest) (*WithdrawApplicationReply, error)
}

func RegisterJobApplicationHTTPServer(s *http.Server, srv JobApplicationHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/applications", _JobApplication_ApplyJob0_HTTP_Handler(srv))
	r.GET("/api/v1/applications/{id}", _JobApplication_GetApplication0_HTTP_Handler(srv))
	r.GET("/api/v1/users/applications", _JobApplication_ListUserApplications0_HTTP_Handler(srv))
	r.GET("/api/v1/jobs/{job_id}/applications", _JobApplication_ListJobApplications0_HTTP_Handler(srv))
	r.PUT("/api/v1/applications/{id}/status", _JobApplication_UpdateApplicationStatus0_HTTP_Handler(srv))
	r.DELETE("/api/v1/applications/{id}", _JobApplication_WithdrawApplication0_HTTP_Handler(srv))
}

func _JobApplication_ApplyJob0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationApplyJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyJob(ctx, req.(*ApplyJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _JobApplication_GetApplication0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationGetApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetApplication(ctx, req.(*GetApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobApplicationDetailReply)
		return ctx.Result(200, reply)
	}
}

func _JobApplication_ListUserApplications0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUserApplicationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationListUserApplications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserApplications(ctx, req.(*ListUserApplicationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationsReply)
		return ctx.Result(200, reply)
	}
}

func _JobApplication_ListJobApplications0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListJobApplicationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationListJobApplications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListJobApplications(ctx, req.(*ListJobApplicationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationsReply)
		return ctx.Result(200, reply)
	}
}

func _JobApplication_UpdateApplicationStatus0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateApplicationStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationUpdateApplicationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApplicationStatus(ctx, req.(*UpdateApplicationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _JobApplication_WithdrawApplication0_HTTP_Handler(srv JobApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WithdrawApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobApplicationWithdrawApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WithdrawApplication(ctx, req.(*WithdrawApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WithdrawApplicationReply)
		return ctx.Result(200, reply)
	}
}

type JobApplicationHTTPClient interface {
	// ApplyJob Apply for a job
	ApplyJob(ctx context.Context, req *ApplyJobRequest, opts ...http.CallOption) (rsp *JobApplicationReply, err error)
	// GetApplication Get application detail
	GetApplication(ctx context.Context, req *GetApplicationRequest, opts ...http.CallOption) (rsp *JobApplicationDetailReply, err error)
	// ListJobApplications List applications for a job posting (for HR)
	ListJobApplications(ctx context.Context, req *ListJobApplicationsRequest, opts ...http.CallOption) (rsp *ListApplicationsReply, err error)
	// ListUserApplications List applications for a user
	ListUserApplications(ctx context.Context, req *ListUserApplicationsRequest, opts ...http.CallOption) (rsp *ListApplicationsReply, err error)
	// UpdateApplicationStatus Update application status (for HR)
	UpdateApplicationStatus(ctx context.Context, req *UpdateApplicationStatusRequest, opts ...http.CallOption) (rsp *JobApplicationReply, err error)
	// WithdrawApplication Withdraw application (for user)
	WithdrawApplication(ctx context.Context, req *WithdrawApplicationRequest, opts ...http.CallOption) (rsp *WithdrawApplicationReply, err error)
}

type JobApplicationHTTPClientImpl struct {
	cc *http.Client
}

func NewJobApplicationHTTPClient(client *http.Client) JobApplicationHTTPClient {
	return &JobApplicationHTTPClientImpl{client}
}

// ApplyJob Apply for a job
func (c *JobApplicationHTTPClientImpl) ApplyJob(ctx context.Context, in *ApplyJobRequest, opts ...http.CallOption) (*JobApplicationReply, error) {
	var out JobApplicationReply
	pattern := "/api/v1/applications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobApplicationApplyJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetApplication Get application detail
func (c *JobApplicationHTTPClientImpl) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...http.CallOption) (*JobApplicationDetailReply, error) {
	var out JobApplicationDetailReply
	pattern := "/api/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobApplicationGetApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListJobApplications List applications for a job posting (for HR)
func (c *JobApplicationHTTPClientImpl) ListJobApplications(ctx context.Context, in *ListJobApplicationsRequest, opts ...http.CallOption) (*ListApplicationsReply, error) {
	var out ListApplicationsReply
	pattern := "/api/v1/jobs/{job_id}/applications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobApplicationListJobApplications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUserApplications List applications for a user
func (c *JobApplicationHTTPClientImpl) ListUserApplications(ctx context.Context, in *ListUserApplicationsRequest, opts ...http.CallOption) (*ListApplicationsReply, error) {
	var out ListApplicationsReply
	pattern := "/api/v1/users/applications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobApplicationListUserApplications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateApplicationStatus Update application status (for HR)
func (c *JobApplicationHTTPClientImpl) UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...http.CallOption) (*JobApplicationReply, error) {
	var out JobApplicationReply
	pattern := "/api/v1/applications/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobApplicationUpdateApplicationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WithdrawApplication Withdraw application (for user)
func (c *JobApplicationHTTPClientImpl) WithdrawApplication(ctx context.Context, in *WithdrawApplicationRequest, opts ...http.CallOption) (*WithdrawApplicationReply, error) {
	var out WithdrawApplicationReply
	pattern := "/api/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobApplicationWithdrawApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
