// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: application/v1/application.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationStatus int32

const (
	ApplicationStatus_APPLIED   ApplicationStatus = 0
	ApplicationStatus_REVIEWING ApplicationStatus = 1
	ApplicationStatus_ACCEPTED  ApplicationStatus = 2
	ApplicationStatus_REJECTED  ApplicationStatus = 3
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLIED",
		1: "REVIEWING",
		2: "ACCEPTED",
		3: "REJECTED",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLIED":   0,
		"REVIEWING": 1,
		"ACCEPTED":  2,
		"REJECTED":  3,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_application_v1_application_proto_enumTypes[0].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_application_v1_application_proto_enumTypes[0]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{0}
}

// Basic application info (without full resume detail)
type JobApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ApplicantName string                 `protobuf:"bytes,5,opt,name=applicant_name,json=applicantName,proto3" json:"applicant_name,omitempty"`
	University    string                 `protobuf:"bytes,6,opt,name=university,proto3" json:"university,omitempty"`
	Status        ApplicationStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=api.application.v1.ApplicationStatus" json:"status,omitempty"`
	AppliedAt     string                 `protobuf:"bytes,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HrNote        string                 `protobuf:"bytes,10,opt,name=hr_note,json=hrNote,proto3" json:"hr_note,omitempty"`
	// Job info
	JobInfo       *JobInfo `protobuf:"bytes,11,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplicationInfo) Reset() {
	*x = JobApplicationInfo{}
	mi := &file_application_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationInfo) ProtoMessage() {}

func (x *JobApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationInfo.ProtoReflect.Descriptor instead.
func (*JobApplicationInfo) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *JobApplicationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobApplicationInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JobApplicationInfo) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *JobApplicationInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobApplicationInfo) GetApplicantName() string {
	if x != nil {
		return x.ApplicantName
	}
	return ""
}

func (x *JobApplicationInfo) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *JobApplicationInfo) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLIED
}

func (x *JobApplicationInfo) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

func (x *JobApplicationInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *JobApplicationInfo) GetHrNote() string {
	if x != nil {
		return x.HrNote
	}
	return ""
}

func (x *JobApplicationInfo) GetJobInfo() *JobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

// Full application detail (with resume detail)
type JobApplicationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ApplicantName string                 `protobuf:"bytes,5,opt,name=applicant_name,json=applicantName,proto3" json:"applicant_name,omitempty"`
	University    string                 `protobuf:"bytes,6,opt,name=university,proto3" json:"university,omitempty"`
	Status        ApplicationStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=api.application.v1.ApplicationStatus" json:"status,omitempty"`
	AppliedAt     string                 `protobuf:"bytes,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HrNote        string                 `protobuf:"bytes,10,opt,name=hr_note,json=hrNote,proto3" json:"hr_note,omitempty"`
	// Full resume detail
	ResumeDetail *ResumeDetail `protobuf:"bytes,11,opt,name=resume_detail,json=resumeDetail,proto3" json:"resume_detail,omitempty"`
	// Job info
	JobInfo       *JobInfo `protobuf:"bytes,12,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplicationDetail) Reset() {
	*x = JobApplicationDetail{}
	mi := &file_application_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplicationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationDetail) ProtoMessage() {}

func (x *JobApplicationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationDetail.ProtoReflect.Descriptor instead.
func (*JobApplicationDetail) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{1}
}

func (x *JobApplicationDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobApplicationDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JobApplicationDetail) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *JobApplicationDetail) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobApplicationDetail) GetApplicantName() string {
	if x != nil {
		return x.ApplicantName
	}
	return ""
}

func (x *JobApplicationDetail) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *JobApplicationDetail) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLIED
}

func (x *JobApplicationDetail) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

func (x *JobApplicationDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *JobApplicationDetail) GetHrNote() string {
	if x != nil {
		return x.HrNote
	}
	return ""
}

func (x *JobApplicationDetail) GetResumeDetail() *ResumeDetail {
	if x != nil {
		return x.ResumeDetail
	}
	return nil
}

func (x *JobApplicationDetail) GetJobInfo() *JobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

type ResumeDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Summary        string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills         []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Education      []*Education           `protobuf:"bytes,6,rep,name=education,proto3" json:"education,omitempty"`
	Experience     []*Experience          `protobuf:"bytes,7,rep,name=experience,proto3" json:"experience,omitempty"`
	Projects       []*Project             `protobuf:"bytes,8,rep,name=projects,proto3" json:"projects,omitempty"`
	Certifications []string               `protobuf:"bytes,9,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Languages      []string               `protobuf:"bytes,10,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeDetail) Reset() {
	*x = ResumeDetail{}
	mi := &file_application_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDetail) ProtoMessage() {}

func (x *ResumeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDetail.ProtoReflect.Descriptor instead.
func (*ResumeDetail) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResumeDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResumeDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeDetail) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ResumeDetail) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ResumeDetail) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ResumeDetail) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *ResumeDetail) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type Education struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Degree         string                 `protobuf:"bytes,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Institution    string                 `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	GraduationYear string                 `protobuf:"bytes,3,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_application_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetGraduationYear() string {
	if x != nil {
		return x.GraduationYear
	}
	return ""
}

func (x *Education) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Experience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company          string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Duration         string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Responsibilities []string               `protobuf:"bytes,4,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Achievements     []string               `protobuf:"bytes,5,rep,name=achievements,proto3" json:"achievements,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_application_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *Experience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Experience) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *Experience) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Technologies  []string               `protobuf:"bytes,3,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Achievements  []string               `protobuf:"bytes,7,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_application_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Project) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Project) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Project) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Project) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_application_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *JobInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *JobInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ApplyJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyJobRequest) Reset() {
	*x = ApplyJobRequest{}
	mi := &file_application_v1_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJobRequest) ProtoMessage() {}

func (x *ApplyJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJobRequest.ProtoReflect.Descriptor instead.
func (*ApplyJobRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ApplyJobRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type JobApplicationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *JobApplicationInfo    `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplicationReply) Reset() {
	*x = JobApplicationReply{}
	mi := &file_application_v1_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplicationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationReply) ProtoMessage() {}

func (x *JobApplicationReply) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationReply.ProtoReflect.Descriptor instead.
func (*JobApplicationReply) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{8}
}

func (x *JobApplicationReply) GetApplication() *JobApplicationInfo {
	if x != nil {
		return x.Application
	}
	return nil
}

type JobApplicationDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *JobApplicationDetail  `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobApplicationDetailReply) Reset() {
	*x = JobApplicationDetailReply{}
	mi := &file_application_v1_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobApplicationDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobApplicationDetailReply) ProtoMessage() {}

func (x *JobApplicationDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobApplicationDetailReply.ProtoReflect.Descriptor instead.
func (*JobApplicationDetailReply) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{9}
}

func (x *JobApplicationDetailReply) GetApplication() *JobApplicationDetail {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUserApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserApplicationsRequest) Reset() {
	*x = ListUserApplicationsRequest{}
	mi := &file_application_v1_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserApplicationsRequest) ProtoMessage() {}

func (x *ListUserApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListUserApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserApplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListJobApplicationsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Page     int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional filter by status
	Status        ApplicationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.application.v1.ApplicationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobApplicationsRequest) Reset() {
	*x = ListJobApplicationsRequest{}
	mi := &file_application_v1_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobApplicationsRequest) ProtoMessage() {}

func (x *ListJobApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListJobApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobApplicationsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ListJobApplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobApplicationsRequest) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLIED
}

type ListApplicationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*JobApplicationInfo  `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsReply) Reset() {
	*x = ListApplicationsReply{}
	mi := &file_application_v1_application_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsReply) ProtoMessage() {}

func (x *ListApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsReply.ProtoReflect.Descriptor instead.
func (*ListApplicationsReply) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{13}
}

func (x *ListApplicationsReply) GetApplications() []*JobApplicationInfo {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListApplicationsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicationsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateApplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        ApplicationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=api.application.v1.ApplicationStatus" json:"status,omitempty"`
	HrNote        string                 `protobuf:"bytes,3,opt,name=hr_note,json=hrNote,proto3" json:"hr_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationStatusRequest) Reset() {
	*x = UpdateApplicationStatusRequest{}
	mi := &file_application_v1_application_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusRequest) ProtoMessage() {}

func (x *UpdateApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateApplicationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicationStatusRequest) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLIED
}

func (x *UpdateApplicationStatusRequest) GetHrNote() string {
	if x != nil {
		return x.HrNote
	}
	return ""
}

type WithdrawApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawApplicationRequest) Reset() {
	*x = WithdrawApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawApplicationRequest) ProtoMessage() {}

func (x *WithdrawApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawApplicationRequest.ProtoReflect.Descriptor instead.
func (*WithdrawApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{15}
}

func (x *WithdrawApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WithdrawApplicationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawApplicationReply) Reset() {
	*x = WithdrawApplicationReply{}
	mi := &file_application_v1_application_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawApplicationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawApplicationReply) ProtoMessage() {}

func (x *WithdrawApplicationReply) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawApplicationReply.ProtoReflect.Descriptor instead.
func (*WithdrawApplicationReply) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{16}
}

func (x *WithdrawApplicationReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawApplicationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_application_v1_application_proto protoreflect.FileDescriptor

const file_application_v1_application_proto_rawDesc = "" +
	"\n" +
	" application/v1/application.proto\x12\x12api.application.v1\x1a\x1cgoogle/api/annotations.proto\"\x86\x03\n" +
	"\x12JobApplicationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12%\n" +
	"\x0eapplicant_name\x18\x05 \x01(\tR\rapplicantName\x12\x1e\n" +
	"\n" +
	"university\x18\x06 \x01(\tR\n" +
	"university\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.api.application.v1.ApplicationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"applied_at\x18\b \x01(\tR\tappliedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x17\n" +
	"\ahr_note\x18\n" +
	" \x01(\tR\x06hrNote\x126\n" +
	"\bjob_info\x18\v \x01(\v2\x1b.api.application.v1.JobInfoR\ajobInfo\"\xcf\x03\n" +
	"\x14JobApplicationDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12%\n" +
	"\x0eapplicant_name\x18\x05 \x01(\tR\rapplicantName\x12\x1e\n" +
	"\n" +
	"university\x18\x06 \x01(\tR\n" +
	"university\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.api.application.v1.ApplicationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"applied_at\x18\b \x01(\tR\tappliedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x17\n" +
	"\ahr_note\x18\n" +
	" \x01(\tR\x06hrNote\x12E\n" +
	"\rresume_detail\x18\v \x01(\v2 .api.application.v1.ResumeDetailR\fresumeDetail\x126\n" +
	"\bjob_info\x18\f \x01(\v2\x1b.api.application.v1.JobInfoR\ajobInfo\"\xfc\x02\n" +
	"\fResumeDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12;\n" +
	"\teducation\x18\x06 \x03(\v2\x1d.api.application.v1.EducationR\teducation\x12>\n" +
	"\n" +
	"experience\x18\a \x03(\v2\x1e.api.application.v1.ExperienceR\n" +
	"experience\x127\n" +
	"\bprojects\x18\b \x03(\v2\x1b.api.application.v1.ProjectR\bprojects\x12&\n" +
	"\x0ecertifications\x18\t \x03(\tR\x0ecertifications\x12\x1c\n" +
	"\tlanguages\x18\n" +
	" \x03(\tR\tlanguages\"\x90\x01\n" +
	"\tEducation\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\tR\x06degree\x12 \n" +
	"\vinstitution\x18\x02 \x01(\tR\vinstitution\x12'\n" +
	"\x0fgraduation_year\x18\x03 \x01(\tR\x0egraduationYear\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xca\x01\n" +
	"\n" +
	"Experience\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12*\n" +
	"\x10responsibilities\x18\x04 \x03(\tR\x10responsibilities\x12\"\n" +
	"\fachievements\x18\x05 \x03(\tR\fachievements\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xc9\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\ftechnologies\x18\x03 \x03(\tR\ftechnologies\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\"\n" +
	"\fachievements\x18\a \x03(\tR\fachievements\"n\n" +
	"\aJobInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"E\n" +
	"\x0fApplyJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\"_\n" +
	"\x13JobApplicationReply\x12H\n" +
	"\vapplication\x18\x01 \x01(\v2&.api.application.v1.JobApplicationInfoR\vapplication\"g\n" +
	"\x19JobApplicationDetailReply\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2(.api.application.v1.JobApplicationDetailR\vapplication\"'\n" +
	"\x15GetApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x1bListUserApplicationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa3\x01\n" +
	"\x1aListJobApplicationsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.api.application.v1.ApplicationStatusR\x06status\"\xaa\x01\n" +
	"\x15ListApplicationsReply\x12J\n" +
	"\fapplications\x18\x01 \x03(\v2&.api.application.v1.JobApplicationInfoR\fapplications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x88\x01\n" +
	"\x1eUpdateApplicationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.api.application.v1.ApplicationStatusR\x06status\x12\x17\n" +
	"\ahr_note\x18\x03 \x01(\tR\x06hrNote\",\n" +
	"\x1aWithdrawApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x18WithdrawApplicationReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*K\n" +
	"\x11ApplicationStatus\x12\v\n" +
	"\aAPPLIED\x10\x00\x12\r\n" +
	"\tREVIEWING\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x032\x92\a\n" +
	"\x0eJobApplication\x12y\n" +
	"\bApplyJob\x12#.api.application.v1.ApplyJobRequest\x1a'.api.application.v1.JobApplicationReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/applications\x12\x8d\x01\n" +
	"\x0eGetApplication\x12).api.application.v1.GetApplicationRequest\x1a-.api.application.v1.JobApplicationDetailReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/applications/{id}\x12\x96\x01\n" +
	"\x14ListUserApplications\x12/.api.application.v1.ListUserApplicationsRequest\x1a).api.application.v1.ListApplicationsReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/users/applications\x12\x9c\x01\n" +
	"\x13ListJobApplications\x12..api.application.v1.ListJobApplicationsRequest\x1a).api.application.v1.ListApplicationsReply\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/jobs/{job_id}/applications\x12\xa3\x01\n" +
	"\x17UpdateApplicationStatus\x122.api.application.v1.UpdateApplicationStatusRequest\x1a'.api.application.v1.JobApplicationReply\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/v1/applications/{id}/status\x12\x96\x01\n" +
	"\x13WithdrawApplication\x12..api.application.v1.WithdrawApplicationRequest\x1a,.api.application.v1.WithdrawApplicationReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/applications/{id}B6\n" +
	"\x12api.application.v1P\x01Z\x1eJobblyBE/api/application/v1;v1b\x06proto3"

var (
	file_application_v1_application_proto_rawDescOnce sync.Once
	file_application_v1_application_proto_rawDescData []byte
)

func file_application_v1_application_proto_rawDescGZIP() []byte {
	file_application_v1_application_proto_rawDescOnce.Do(func() {
		file_application_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_v1_application_proto_rawDesc), len(file_application_v1_application_proto_rawDesc)))
	})
	return file_application_v1_application_proto_rawDescData
}

var file_application_v1_application_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_application_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_application_v1_application_proto_goTypes = []any{
	(ApplicationStatus)(0),                 // 0: api.application.v1.ApplicationStatus
	(*JobApplicationInfo)(nil),             // 1: api.application.v1.JobApplicationInfo
	(*JobApplicationDetail)(nil),           // 2: api.application.v1.JobApplicationDetail
	(*ResumeDetail)(nil),                   // 3: api.application.v1.ResumeDetail
	(*Education)(nil),                      // 4: api.application.v1.Education
	(*Experience)(nil),                     // 5: api.application.v1.Experience
	(*Project)(nil),                        // 6: api.application.v1.Project
	(*JobInfo)(nil),                        // 7: api.application.v1.JobInfo
	(*ApplyJobRequest)(nil),                // 8: api.application.v1.ApplyJobRequest
	(*JobApplicationReply)(nil),            // 9: api.application.v1.JobApplicationReply
	(*JobApplicationDetailReply)(nil),      // 10: api.application.v1.JobApplicationDetailReply
	(*GetApplicationRequest)(nil),          // 11: api.application.v1.GetApplicationRequest
	(*ListUserApplicationsRequest)(nil),    // 12: api.application.v1.ListUserApplicationsRequest
	(*ListJobApplicationsRequest)(nil),     // 13: api.application.v1.ListJobApplicationsRequest
	(*ListApplicationsReply)(nil),          // 14: api.application.v1.ListApplicationsReply
	(*UpdateApplicationStatusRequest)(nil), // 15: api.application.v1.UpdateApplicationStatusRequest
	(*WithdrawApplicationRequest)(nil),     // 16: api.application.v1.WithdrawApplicationRequest
	(*WithdrawApplicationReply)(nil),       // 17: api.application.v1.WithdrawApplicationReply
}
var file_application_v1_application_proto_depIdxs = []int32{
	0,  // 0: api.application.v1.JobApplicationInfo.status:type_name -> api.application.v1.ApplicationStatus
	7,  // 1: api.application.v1.JobApplicationInfo.job_info:type_name -> api.application.v1.JobInfo
	0,  // 2: api.application.v1.JobApplicationDetail.status:type_name -> api.application.v1.ApplicationStatus
	3,  // 3: api.application.v1.JobApplicationDetail.resume_detail:type_name -> api.application.v1.ResumeDetail
	7,  // 4: api.application.v1.JobApplicationDetail.job_info:type_name -> api.application.v1.JobInfo
	4,  // 5: api.application.v1.ResumeDetail.education:type_name -> api.application.v1.Education
	5,  // 6: api.application.v1.ResumeDetail.experience:type_name -> api.application.v1.Experience
	6,  // 7: api.application.v1.ResumeDetail.projects:type_name -> api.application.v1.Project
	1,  // 8: api.application.v1.JobApplicationReply.application:type_name -> api.application.v1.JobApplicationInfo
	2,  // 9: api.application.v1.JobApplicationDetailReply.application:type_name -> api.application.v1.JobApplicationDetail
	0,  // 10: api.application.v1.ListJobApplicationsRequest.status:type_name -> api.application.v1.ApplicationStatus
	1,  // 11: api.application.v1.ListApplicationsReply.applications:type_name -> api.application.v1.JobApplicationInfo
	0,  // 12: api.application.v1.UpdateApplicationStatusRequest.status:type_name -> api.application.v1.ApplicationStatus
	8,  // 13: api.application.v1.JobApplication.ApplyJob:input_type -> api.application.v1.ApplyJobRequest
	11, // 14: api.application.v1.JobApplication.GetApplication:input_type -> api.application.v1.GetApplicationRequest
	12, // 15: api.application.v1.JobApplication.ListUserApplications:input_type -> api.application.v1.ListUserApplicationsRequest
	13, // 16: api.application.v1.JobApplication.ListJobApplications:input_type -> api.application.v1.ListJobApplicationsRequest
	15, // 17: api.application.v1.JobApplication.UpdateApplicationStatus:input_type -> api.application.v1.UpdateApplicationStatusRequest
	16, // 18: api.application.v1.JobApplication.WithdrawApplication:input_type -> api.application.v1.WithdrawApplicationRequest
	9,  // 19: api.application.v1.JobApplication.ApplyJob:output_type -> api.application.v1.JobApplicationReply
	10, // 20: api.application.v1.JobApplication.GetApplication:output_type -> api.application.v1.JobApplicationDetailReply
	14, // 21: api.application.v1.JobApplication.ListUserApplications:output_type -> api.application.v1.ListApplicationsReply
	14, // 22: api.application.v1.JobApplication.ListJobApplications:output_type -> api.application.v1.ListApplicationsReply
	9,  // 23: api.application.v1.JobApplication.UpdateApplicationStatus:output_type -> api.application.v1.JobApplicationReply
	17, // 24: api.application.v1.JobApplication.WithdrawApplication:output_type -> api.application.v1.WithdrawApplicationReply
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_application_v1_application_proto_init() }
func file_application_v1_application_proto_init() {
	if File_application_v1_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_v1_application_proto_rawDesc), len(file_application_v1_application_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_v1_application_proto_goTypes,
		DependencyIndexes: file_application_v1_application_proto_depIdxs,
		EnumInfos:         file_application_v1_application_proto_enumTypes,
		MessageInfos:      file_application_v1_application_proto_msgTypes,
	}.Build()
	File_application_v1_application_proto = out.File
	file_application_v1_application_proto_goTypes = nil
	file_application_v1_application_proto_depIdxs = nil
}
