// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsErrorReasonUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ERROR_REASON_UNSPECIFIED.String() && e.Code == 500
}

func ErrorErrorReasonUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ERROR_REASON_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsSystemError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SYSTEM_ERROR.String() && e.Code == 500
}

func ErrorSystemError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SYSTEM_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsAuthError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_ERROR.String() && e.Code == 401
}

func ErrorAuthError(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_AUTH_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsDataRequestInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_REQUEST_INVALID.String() && e.Code == 400
}

func ErrorDataRequestInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_REQUEST_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsNotificationNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NOTIFICATION_NOT_FOUND.String() && e.Code == 404
}

func ErrorNotificationNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_NOTIFICATION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// JWT Authentication Errors
func IsJwtTokenMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_TOKEN_MISSING.String() && e.Code == 401
}

// JWT Authentication Errors
func ErrorJwtTokenMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_TOKEN_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsJwtTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorJwtTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsJwtTokenExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_TOKEN_EXPIRED.String() && e.Code == 401
}

func ErrorJwtTokenExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_TOKEN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsJwtTokenNotActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_TOKEN_NOT_ACTIVE.String() && e.Code == 401
}

func ErrorJwtTokenNotActive(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_TOKEN_NOT_ACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsJwtTokenMalformed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_TOKEN_MALFORMED.String() && e.Code == 401
}

func ErrorJwtTokenMalformed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_TOKEN_MALFORMED.String(), fmt.Sprintf(format, args...))
}

func IsJwtClaimsInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JWT_CLAIMS_INVALID.String() && e.Code == 401
}

func ErrorJwtClaimsInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_JWT_CLAIMS_INVALID.String(), fmt.Sprintf(format, args...))
}

// User Authentication Errors
func IsInvalidCredentials(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_CREDENTIALS.String() && e.Code == 401
}

// User Authentication Errors
func ErrorInvalidCredentials(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_INVALID_CREDENTIALS.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_USER_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsEmailAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EMAIL_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorEmailAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_EMAIL_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsPhoneAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PHONE_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorPhoneAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_PHONE_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsWeakPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WEAK_PASSWORD.String() && e.Code == 400
}

func ErrorWeakPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_WEAK_PASSWORD.String(), fmt.Sprintf(format, args...))
}

func IsInvalidEmailFormat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_EMAIL_FORMAT.String() && e.Code == 400
}

func ErrorInvalidEmailFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_EMAIL_FORMAT.String(), fmt.Sprintf(format, args...))
}

func IsInvalidPhoneFormat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PHONE_FORMAT.String() && e.Code == 400
}

func ErrorInvalidPhoneFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PHONE_FORMAT.String(), fmt.Sprintf(format, args...))
}

// Authorization Errors
func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNAUTHORIZED.String() && e.Code == 401
}

// Authorization Errors
func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UNAUTHORIZED.String(), fmt.Sprintf(format, args...))
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FORBIDDEN.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

func IsPermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PERMISSION_DENIED.String() && e.Code == 403
}

func ErrorPermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}
