// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: auth/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	ErrorReason_SYSTEM_ERROR             ErrorReason = 1
	ErrorReason_AUTH_ERROR               ErrorReason = 2
	ErrorReason_DATA_REQUEST_INVALID     ErrorReason = 3
	ErrorReason_USER_NOT_FOUND           ErrorReason = 4
	ErrorReason_NOTIFICATION_NOT_FOUND   ErrorReason = 5
	// JWT Authentication Errors
	ErrorReason_JWT_TOKEN_MISSING    ErrorReason = 10
	ErrorReason_JWT_TOKEN_INVALID    ErrorReason = 11
	ErrorReason_JWT_TOKEN_EXPIRED    ErrorReason = 12
	ErrorReason_JWT_TOKEN_NOT_ACTIVE ErrorReason = 13
	ErrorReason_JWT_TOKEN_MALFORMED  ErrorReason = 14
	ErrorReason_JWT_CLAIMS_INVALID   ErrorReason = 15
	// User Authentication Errors
	ErrorReason_INVALID_CREDENTIALS  ErrorReason = 20
	ErrorReason_USER_ALREADY_EXISTS  ErrorReason = 21
	ErrorReason_EMAIL_ALREADY_EXISTS ErrorReason = 22
	ErrorReason_PHONE_ALREADY_EXISTS ErrorReason = 23
	ErrorReason_WEAK_PASSWORD        ErrorReason = 24
	ErrorReason_INVALID_EMAIL_FORMAT ErrorReason = 25
	ErrorReason_INVALID_PHONE_FORMAT ErrorReason = 26
	// Authorization Errors
	ErrorReason_UNAUTHORIZED      ErrorReason = 30
	ErrorReason_FORBIDDEN         ErrorReason = 31
	ErrorReason_PERMISSION_DENIED ErrorReason = 32
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "SYSTEM_ERROR",
		2:  "AUTH_ERROR",
		3:  "DATA_REQUEST_INVALID",
		4:  "USER_NOT_FOUND",
		5:  "NOTIFICATION_NOT_FOUND",
		10: "JWT_TOKEN_MISSING",
		11: "JWT_TOKEN_INVALID",
		12: "JWT_TOKEN_EXPIRED",
		13: "JWT_TOKEN_NOT_ACTIVE",
		14: "JWT_TOKEN_MALFORMED",
		15: "JWT_CLAIMS_INVALID",
		20: "INVALID_CREDENTIALS",
		21: "USER_ALREADY_EXISTS",
		22: "EMAIL_ALREADY_EXISTS",
		23: "PHONE_ALREADY_EXISTS",
		24: "WEAK_PASSWORD",
		25: "INVALID_EMAIL_FORMAT",
		26: "INVALID_PHONE_FORMAT",
		30: "UNAUTHORIZED",
		31: "FORBIDDEN",
		32: "PERMISSION_DENIED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"SYSTEM_ERROR":             1,
		"AUTH_ERROR":               2,
		"DATA_REQUEST_INVALID":     3,
		"USER_NOT_FOUND":           4,
		"NOTIFICATION_NOT_FOUND":   5,
		"JWT_TOKEN_MISSING":        10,
		"JWT_TOKEN_INVALID":        11,
		"JWT_TOKEN_EXPIRED":        12,
		"JWT_TOKEN_NOT_ACTIVE":     13,
		"JWT_TOKEN_MALFORMED":      14,
		"JWT_CLAIMS_INVALID":       15,
		"INVALID_CREDENTIALS":      20,
		"USER_ALREADY_EXISTS":      21,
		"EMAIL_ALREADY_EXISTS":     22,
		"PHONE_ALREADY_EXISTS":     23,
		"WEAK_PASSWORD":            24,
		"INVALID_EMAIL_FORMAT":     25,
		"INVALID_PHONE_FORMAT":     26,
		"UNAUTHORIZED":             30,
		"FORBIDDEN":                31,
		"PERMISSION_DENIED":        32,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_auth_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_auth_v1_error_reason_proto protoreflect.FileDescriptor

const file_auth_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1aauth/v1/error_reason.proto\x12\vapi.auth.v1\x1a\x13errors/errors.proto*\x90\x05\n" +
	"\vErrorReason\x12\"\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x16\n" +
	"\fSYSTEM_ERROR\x10\x01\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\n" +
	"AUTH_ERROR\x10\x02\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x14DATA_REQUEST_INVALID\x10\x03\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x04\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16NOTIFICATION_NOT_FOUND\x10\x05\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x11JWT_TOKEN_MISSING\x10\n" +
	"\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11JWT_TOKEN_INVALID\x10\v\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11JWT_TOKEN_EXPIRED\x10\f\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x14JWT_TOKEN_NOT_ACTIVE\x10\r\x1a\x04\xa8E\x91\x03\x12\x1d\n" +
	"\x13JWT_TOKEN_MALFORMED\x10\x0e\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12JWT_CLAIMS_INVALID\x10\x0f\x1a\x04\xa8E\x91\x03\x12\x1d\n" +
	"\x13INVALID_CREDENTIALS\x10\x14\x1a\x04\xa8E\x91\x03\x12\x1d\n" +
	"\x13USER_ALREADY_EXISTS\x10\x15\x1a\x04\xa8E\x99\x03\x12\x1e\n" +
	"\x14EMAIL_ALREADY_EXISTS\x10\x16\x1a\x04\xa8E\x99\x03\x12\x1e\n" +
	"\x14PHONE_ALREADY_EXISTS\x10\x17\x1a\x04\xa8E\x99\x03\x12\x17\n" +
	"\rWEAK_PASSWORD\x10\x18\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14INVALID_EMAIL_FORMAT\x10\x19\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14INVALID_PHONE_FORMAT\x10\x1a\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x1e\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x1f\x1a\x04\xa8E\x93\x03\x12\x1b\n" +
	"\x11PERMISSION_DENIED\x10 \x1a\x04\xa8E\x93\x03B(\n" +
	"\vapi.auth.v1P\x01Z\x17JobblyBE/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_error_reason_proto_rawDescOnce sync.Once
	file_auth_v1_error_reason_proto_rawDescData []byte
)

func file_auth_v1_error_reason_proto_rawDescGZIP() []byte {
	file_auth_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_auth_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_error_reason_proto_rawDesc), len(file_auth_v1_error_reason_proto_rawDesc)))
	})
	return file_auth_v1_error_reason_proto_rawDescData
}

var file_auth_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.auth.v1.ErrorReason
}
var file_auth_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_error_reason_proto_init() }
func file_auth_v1_error_reason_proto_init() {
	if File_auth_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_error_reason_proto_rawDesc), len(file_auth_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_auth_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_auth_v1_error_reason_proto_enumTypes,
	}.Build()
	File_auth_v1_error_reason_proto = out.File
	file_auth_v1_error_reason_proto_goTypes = nil
	file_auth_v1_error_reason_proto_depIdxs = nil
}
